//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spqw.rc
//
#define IDR_MAINFRAME                   2
#define IDP_TOO_MANY_ROWS               4
#define IDS_PSTATUS_NULL                5
#define IDS_PSTATUS_OFFLINE             6
#define IDS_PSTATUS_ERROR               7
#define IDS_PSTATUS_HALT                8
#define IDS_PSTATUS_INIT                9
#define IDS_PSTATUS_WAIT                10
#define IDS_PSTATUS_SHUTD               11
#define IDS_PSTATUS_RUN                 12
#define IDS_PSTATUS_OPER                13
#define IDP_NOJOBSELECTED               14
#define IDP_NOPTRSELECTED               15
#define IDP_NOSEARCHSTR                 16
#define IDP_NOTFOUND                    17
#define IDP_XTENQ_PASSREQ               50
#define IDP_XTENQ_BADPASSWD             51
#define IDP_XTENQ_UNKNOWN               52
#define IDP_XTENQ_BADCLIENT             53
#define IDP_XTENQ_UNKNOWNU              54
#define IDP_CONNDIED                    56
#define IDR_JOBS                        90
#define IDR_PTR                         91
#define IDR_VIEWJOB                     92
#define IDD_ABOUTBOX                    100
#define IDD_BATFILE                     101
#define IDD_EDITFMT                     102
#define IDD_EDITSEP                     103
#define IDD_FORMATDEF                   104
#define IDD_FORMCPS                     105
#define IDD_JOBFILE                     106
#define IDD_LOGINHOST                   107
#define IDD_NETSTATS                    108
#define IDD_ORESTRICT22                 109
#define IDD_PAGE                        110
#define IDD_PRFORM                      111
#define IDD_PROGOPTS                    112
#define IDD_RETAIN                      113
#define IDS_JANUARY                     113
#define IDD_SEARCHDATA                  114
#define IDS_FEBRUARY                    114
#define IDD_SEARCHJP                    115
#define IDS_MARCH                       115
#define IDD_SECURITY22                  116
#define IDS_APRIL                       116
#define IDD_USERMAIL                    117
#define IDS_MAY                         117
#define IDD_USERPERM                    118
#define IDS_JUNE                        118
#define IDD_VIEWMENU                    119
#define IDS_JULY                        119
#define IDS_AUGUST                      120
#define IDR_JOBFLOAT                    120
#define IDS_SEPTEMBER                   121
#define IDR_PTRFLOAT                    121
#define IDS_OCTOBER                     122
#define IDS_NOVEMBER                    123
#define IDS_DECEMBER                    124
#define IDS_SUNDAY                      125
#define IDS_MONDAY                      126
#define IDS_TUESDAY                     127
#define IDS_WEDNESDAY                   128
#define IDS_THURSDAY                    129
#define IDS_FRIDAY                      130
#define IDS_SATURDAY                    131
#define IDS_LOCALPTR                    140
#define IDS_PHADAB                      141
#define IDS_PNALIGN                     142
#define IDS_PHEOJ                       143
#define IDS_INTER                       144
#define ID_INDICATOR_STARTP             150
#define IDC_FMTCODE                     150
#define ID_INDICATOR_ENDP               151
#define IDC_WIDTH                       151
#define ID_INDICATOR_HATP               152
#define IDC_SCR_WIDTH                   152
#define IDC_TABLEFT                     153
#define IDC_SKIPRIGHT                   154
#define IDC_SEPVALUE                    155
#define IDC_WHAT4                       156
#define IDC_FMTLIST                     157
#define IDC_NEWFMT                      158
#define IDC_NEWSEP                      159
#define IDC_EDITFMT                     160
#define IDC_DELFMT                      161
#define IDC_RESETDEFLT                  162
#define IDC_FORMTYPE                    163
#define IDC_HEADER                      164
#define IDC_SUPPH                       165
#define IDC_PRINTER                     166
#define IDC_COPIES                      167
#define IDC_SCR_COPIES                  168
#define IDC_PRIORITY                    169
#define IDC_SCR_PRIORITY                170
#define IDC_UNIXHOST                    171
#define IDC_CLIENTHOST                  172
#define IDC_USER                        173
#define IDC_PASSWD                      174
#define IDC_HOST                        175
#define IDC_NS_PROBESENT                176
#define IDC_CONNECTED                   177
#define IDC_NS_SYNCREQ                  178
#define IDC_NS_SYNCDONE                 179
#define IDC_OPTR                        180
#define IDC_OUSER                       181
#define IDC_OTITLE                      182
#define IDC_PUNPRESTR                   183
#define IDC_ALLJOBS                     184
#define IDC_UNPJOBS                     185
#define IDC_PJOBS                       186
#define IDC_JINCNONULL                  187
#define IDC_JINCNULL                    188
#define IDC_JINCALL                     189
#define IDC_SETALL                      190
#define IDC_CLEARALL                    191
#define IDC_CC_A                        192
#define IDC_CC_B                        193
#define IDC_CC_C                        194
#define IDC_CC_D                        195
#define IDC_CC_E                        196
#define IDC_CC_F                        197
#define IDC_CC_G                        198
#define IDC_CC_H                        199
#define IDC_CC_I                        200
#define IDC_CC_J                        201
#define IDC_CC_K                        202
#define IDC_CC_L                        203
#define IDC_CC_M                        204
#define IDC_CC_N                        205
#define IDC_CC_O                        206
#define IDC_CC_P                        207
#define IDC_CC_A2                       208
#define IDC_CC_B2                       209
#define IDC_CC_C2                       210
#define IDC_CC_D2                       211
#define IDC_CC_E2                       212
#define IDC_CC_F2                       213
#define IDC_CC_G2                       214
#define IDC_CC_H2                       215
#define IDC_CC_I2                       216
#define IDC_CC_J2                       217
#define IDC_CC_K2                       218
#define IDC_CC_L2                       219
#define IDC_CC_M2                       220
#define IDC_CC_N2                       221
#define IDC_CC_O2                       222
#define IDC_CC_P2                       223
#define IDC_LOCALONLY                   224
#define IDC_STARTP                      225
#define IDC_SCR_STARTP                  226
#define IDC_ENDP                        227
#define IDC_SCR_ENDP                    228
#define IDC_HATP                        229
#define IDC_SCR_HATP                    230
#define IDC_ALLP                        231
#define IDC_ODDP                        232
#define IDC_EVENP                       233
#define IDC_SWAPOE                      234
#define IDC_PPFLAGS                     235
#define IDC_NEVER                       236
#define IDC_UNPRINTED                   237
#define IDC_ALWAYS                      238
#define IDC_PROBE_IGNORE                239
#define IDC_PROBE_WARN                  240
#define IDC_SJXBC                       241
#define IDC_SJBAT                       242
#define IDC_POLLTIME                    243
#define IDC_SCR_POLLTIME                244
#define IDC_RETAIN                      245
#define IDC_PRINTED                     246
#define IDC_DIP                         247
#define IDC_SCR_DIP                     248
#define IDC_DINP                        249
#define IDC_SCR_DINP                    250
#define IDC_HOLD                        251
#define IDC_HOUR                        252
#define IDC_MIN                         253
#define IDC_WDAY                        254
#define IDC_MDAY                        255
#define IDC_MON                         256
#define IDC_SCR_HOUR                    257
#define IDC_SCR_MIN                     258
#define IDC_SCR_WDAY                    259
#define IDC_SCR_MDAY                    260
#define IDC_SCR_MON                     261
#define IDC_COLON                       262
#define IDC_LOOKFOR                     263
#define IDC_SEARCH_FORWARD              264
#define IDC_COLON3                      264
#define IDC_SEARCH_BACK                 265
#define IDC_WRAPROUND                   266
#define IDC_IGNORECASE                  267
#define IDC_SRCH_USER                   268
#define IDC_SRCH_JTITLE                 269
#define IDC_SRCH_FORMTYPE               270
#define IDC_SRCH_DEVICE                 271
#define IDC_SRCH_PRINTER                272
#define IDC_MAIL                        273
#define IDC_WRITE                       274
#define IDC_MATTN                       275
#define IDC_WATTN                       276
#define IDC_MINP                        277
#define IDC_DEFP                        278
#define IDC_MAXP                        279
#define IDC_FORMALLOW                   280
#define IDC_DEFPRINTER                  281
#define IDC_PTRALLOW                    282
#define IDC_REMOTEJ                     283
#define IDC_FORMS                       284
#define IDC_CDEFLT                      285
#define IDC_CPRIO                       286
#define IDC_ANYPRIO                     287
#define IDC_UNQUEUE                     288
#define IDC_OTHERJ                      289
#define IDC_VOTHERJ                     290
#define IDC_SSTOP                       291
#define IDC_COVER                       292
#define IDC_ADMIN                       293
#define IDC_PRINQ                       294
#define IDC_REMOTEP                     295
#define IDC_HALTGO                      296
#define IDC_ADDDEL                      297
#define IDC_OTHERP                      298
#define IDC_ACCESSOK                    299
#define IDC_FREEZEOK                    300
#define IDC_SETSTART                    301
#define IDC_SETEND                      302
#define IDC_SETHAT                      303
#define IDC_QUITDATA                    304
#define IDC_ABSHOLD                     305
#define IDP_PREVINSTANCE                400
#define IDP_NO_SERVER                   401
#define IDP_NO_HOSTFILE                 402
#define IDP_HF_INVALIDHOST              403
#define IDP_HF_BADTIMEOUT               404
#define IDP_HF_NOALIAS                  405
#define IDP_SK_CCLISTSOCK               406
#define IDP_SK_CCPROBESOCK              407
#define IDP_GSPU_NOSOCK                 408
#define IDP_GSPU_NOBIND                 409
#define IDP_GSPU_NOSEND                 410
#define IDP_GSPU_NORECV                 411
#define IDP_GSPU_NVALID                 412
#define IDP_PROBE_SOCKERR               413
#define IDP_PROBE_BINDERR               414
#define IDP_PROBE_SENDERR               415
#define IDP_WRONGFORM                   416
#define IDP_NOTYOURJ                    417
#define IDP_ACONFA_PRINTED              418
#define IDP_ACONFA_NPRINTED             419
#define IDP_CCONFA_NPRINTED             420
#define IDP_NOPRINQ                     421
#define IDP_CONFIRM_REINSTALIGN         422
#define IDP_PRIN_CANTCCC                423
#define IDP_PRIN_RUNNING                424
#define IDP_PRIN_CANTGO                 425
#define IDP_PRIN_CANTHALT               426
#define IDP_PRIN_NOTRUNNING             427
#define IDP_CONFIRM_BYPASSALIGN         428
#define IDP_PRIN_CANTINT                429
#define IDP_ASYNCSEL                    430
#define IDP_LISTASYNCSEL                431
#define IDP_PROBEASYNCSEL               432
#define IDP_CCFEEDSOCKET                433
#define IDP_CCOFEEDSOCKET               434
#define IDP_CSFEEDSOCKET                435
#define IDP_CCTEMPFILE                  436
#define IDP_CWTEMPFILE                  437
#define IDP_NOMEMFORPAGES               438
#define IDP_NOMEMFORJOB                 439
#define IDP_INVALIDDOC                  440
#define IDP_JOBTOOWIDE                  441
#define IDP_JOBTOOLONG                  442
#define IDP_STARTPGTENDP                443
#define IDP_SSTARTPGTENDP               444
#define IDP_SENDPLTSTARTP               445
#define IDP_HATPGTENDP                  446
#define IDP_PRINGTNPRIN                 447
#define IDP_ZEROCLASS                   448
#define IDP_JDNOSEARCHS                 449
#define IDP_JDSNOTFOUND                 450
#define IDP_JPNOSEARCHS                 451
#define IDP_JPNOITEM                    452
#define IDP_FOSSILCC                    453
#define IDP_SAVEPROPTS                  454
#define IDP_WRONGPTR                    455
#define IDP_CCJOBQFILE                  456
#define IDP_CWJOBQFILE                  457
#define IDP_CWBATFILE                   458
#define IDP_CDJOBQFILE                  459
#define IDP_CRMSGFILE                   460
#define IDP_ARGDEFERRS                  461
#define IDP_NOCODESEL                   462
#define IDP_TOOMANYFMTS                 463
#define IDS_JFORMAT_A                   500
#define IDS_JFORMAT_C                   502
#define IDS_JFORMAT_F                   505
#define IDS_JFORMAT_H                   507
#define IDS_JFORMAT_K                   510
#define IDS_JFORMAT_L                   511
#define IDS_JFORMAT_N                   513
#define IDS_JFORMAT_O                   514
#define IDS_JFORMAT_P                   515
#define IDS_JFORMAT_Q                   516
#define IDS_JFORMAT_R                   517
#define IDS_JFORMAT_S                   518
#define IDS_JFORMAT_T                   519
#define IDS_JFORMAT_U                   520
#define IDS_JFORMAT_W                   522
#define IDS_JFORMAT_aa                  530
#define IDS_JFORMAT_cc                  532
#define IDS_JFORMAT_ff                  535
#define IDS_JFORMAT_hh                  537
#define IDS_JFORMAT_ll                  541
#define IDS_JFORMAT_mm                  542
#define IDS_JFORMAT_nn                  543
#define IDS_JFORMAT_oo                  544
#define IDS_JFORMAT_pp                  545
#define IDS_JFORMAT_qq                  546
#define IDS_JFORMAT_ss                  548
#define IDS_JFORMAT_tt                  549
#define IDS_JFORMAT_uu                  550
#define IDS_JFORMAT_ww                  552
#define IDS_PFORMAT_aa                  600
#define IDS_PFORMAT_cc                  602
#define IDS_PFORMAT_dd                  603
#define IDS_PFORMAT_ee                  604
#define IDS_PFORMAT_ff                  605
#define IDS_PFORMAT_hh                  607
#define IDS_PFORMAT_ii                  608
#define IDS_PFORMAT_jj                  609
#define IDS_PFORMAT_ll                  611
#define IDS_PFORMAT_mm                  612
#define IDS_PFORMAT_nn                  613
#define IDS_PFORMAT_pp                  615
#define IDS_PFORMAT_ss                  618
#define IDS_PFORMAT_tt                  619
#define IDS_PFORMAT_uu                  620
#define IDS_PFORMAT_ww                  622
#define IDS_PFORMAT_xx                  623
#define IDS_PFORMAT_yy                  624
#define IDS_PFORMAT_zz                  625
#define IDS_DEF_JFMT                    700
#define IDS_DEF_PFMT                    701
#define IDS_EDITINGJFMT                 720
#define IDS_EDITINGPFMT                 721
#define IDS_LOCALONLY                   750
#define IDS_JF_WATTN                    751
#define IDS_JF_MATTN                    752
#define IDS_JF_MAIL                     753
#define IDS_JF_WRITE                    754
#define IDS_JF_ODD                      755
#define IDS_JF_EVEN                     756
#define IDS_JF_SWAP                     758
#define IDS_JF_LOCALONLY                759
#define IDS_JF_RETN                     760
#define IDS_JF_NOH                      761
#define IDS_SJFORMAT_A                  800
#define IDS_SJFORMAT_C                  802
#define IDS_SJFORMAT_F                  805
#define IDS_SJFORMAT_H                  807
#define IDS_SJFORMAT_K                  810
#define IDS_SJFORMAT_L                  811
#define IDS_SJFORMAT_N                  813
#define IDS_SJFORMAT_O                  814
#define IDS_SJFORMAT_P                  815
#define IDS_SJFORMAT_Q                  816
#define IDS_SJFORMAT_R                  817
#define IDS_SJFORMAT_S                  818
#define IDS_SJFORMAT_T                  819
#define IDS_SJFORMAT_U                  820
#define IDS_SJFORMAT_W                  822
#define IDS_SJFORMAT_aa                 830
#define IDS_SJFORMAT_cc                 832
#define IDS_SJFORMAT_ff                 835
#define IDS_SJFORMAT_hh                 837
#define IDS_SJFORMAT_ll                 841
#define IDS_SJFORMAT_mm                 842
#define IDS_SJFORMAT_nn                 843
#define IDS_SJFORMAT_oo                 844
#define IDS_SJFORMAT_pp                 845
#define IDS_SJFORMAT_qq                 846
#define IDS_SJFORMAT_ss                 848
#define IDS_SJFORMAT_tt                 849
#define IDS_SJFORMAT_uu                 850
#define IDS_SJFORMAT_ww                 852
#define IDS_SPFORMAT_aa                 900
#define IDS_SPFORMAT_cc                 902
#define IDS_SPFORMAT_dd                 903
#define IDS_SPFORMAT_ee                 904
#define IDS_SPFORMAT_ff                 905
#define IDS_SPFORMAT_hh                 907
#define IDS_SPFORMAT_ii                 908
#define IDS_SPFORMAT_jj                 909
#define IDS_SPFORMAT_ll                 911
#define IDS_SPFORMAT_mm                 912
#define IDS_SPFORMAT_nn                 913
#define IDS_SPFORMAT_pp                 915
#define IDS_SPFORMAT_ss                 918
#define IDS_SPFORMAT_tt                 919
#define IDS_SPFORMAT_uu                 920
#define IDS_SPFORMAT_ww                 922
#define IDS_SPFORMAT_xx                 923
#define IDS_SPFORMAT_yy                 924
#define IDS_SPFORMAT_zz                 925
#define ID_PRINTERS_FORMTYPE            32788
#define ID_PRINTERS_INTERRUPT           32789
#define ID_PRINTERS_CLASSCODES          32790
#define ID_ACTION_ABORTJOB              32791
#define ID_ACTION_ANOTHERCOPY           32793
#define ID_ACTION_GOPRINTER             32794
#define ID_ACTION_HALTEOJ               32795
#define ID_ACTION_HALTATONCE            32796
#define ID_ACTION_OKALIGNMENT           32797
#define ID_ACTION_DISAPPROVEALIGNMENT   32798
#define ID_JOBS_VIEWJOB                 32799
#define ID_JOBS_FORMANDCOPIES           32800
#define ID_JOBS_PAGES                   32801
#define ID_JOBS_USERANDMAIL             32802
#define ID_JOBS_RETENTION               32803
#define ID_JOBS_CLASSCODES              32804
#define ID_WINDOW_NEWJOBWINDOW          32805
#define ID_WINDOW_NEWPRINTERWINDOW      32806
#define ID_SEARCH_SEARCHFOR             32811
#define ID_SEARCH_SEARCHFORWARD         32812
#define ID_SEARCH_SEARCHBACKWARDS       32813
#define ID_SEARCH_SETSTARTPAGE          32814
#define ID_SEARCH_SETENDPAGE            32815
#define ID_SEARCH_SETHALTEDATPAGE       32816
#define ID_FILE_PROGRAMOPTIONS          32817
#define ID_WINDOW_WINDOWOPTIONS         32818
#define ID_FILE_SAVETOFILE              32819
#define ID_FILE_DISPLAYOPTIONS          32820
#define ID_WINDOW_SETJOBLISTFORMAT      32821
#define ID_WINDOW_SETPRINTERLISTFORMAT  32822
#define ID_JOBS_UNQUEUEJOB              32823
#define ID_JOBS_COPYJOB                 32824
#define ID_JOBS_COPYOPTIONSINJOB        32825
#define ID_FILE_NETWORKSTATS            32826
#define ID_FILE_USERPERMISSIONS         32827
#define ID_WINDOW_SAVEWIDTHSETTINGS     32828
#define ID_WINDOW_PRINTERCOLOURS_PROGRAMNEWWINDOWS_IDLE 32847
#define ID_FILE_PCOLOUR_IDLE            32848
#define ID_FILE_PCOLOUR_PRINTING        32849
#define ID_FILE_PCOLOUR_AWOPER          32850
#define ID_FILE_PCOLOUR_HALTED          32851
#define ID_FILE_PCOLOUR_ERROR           32852
#define ID_FILE_PCOLOUR_OFFLINE         32853
#define ID_FILE_PCOLOUR_STARTUP         32854
#define ID_FILE_PCOLOUR_SHUTD           32855
#define ID_FILE_WPCOLOUR_IDLE           32856
#define ID_FILE_WPCOLOUR_PRINTING       32857
#define ID_FILE_WPCOLOUR_AWOPER         32858
#define ID_FILE_WPCOLOUR_HALTED         32859
#define ID_FILE_WPCOLOUR_ERROR          32860
#define ID_FILE_WPCOLOUR_OFFLINE        32861
#define ID_FILE_WPCOLOUR_STARTUP        32862
#define ID_FILE_WPCOLOUR_SHUTD          32863
#define ID_FILE_PCOLOUR_COPYTOPROG      32864
#define ID_FILE_PCOLOUR_COPYTOWIN       32865

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         32870
#define _APS_NEXT_CONTROL_VALUE         309
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
