# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftpparams.ui'
#
# Created: Tue Sep  1 15:10:55 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ftpparams(object):
    def setupUi(self, ftpparams):
        ftpparams.setObjectName("ftpparams")
        ftpparams.resize(682, 287)
        self.buttonBox = QtGui.QDialogButtonBox(ftpparams)
        self.buttonBox.setGeometry(QtCore.QRect(580, 10, 81, 181))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(ftpparams)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 495, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.outhost = QtGui.QLineEdit(self.layoutWidget)
        self.outhost.setObjectName("outhost")
        self.gridLayout.addWidget(self.outhost, 0, 1, 1, 4)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.portnum = QtGui.QLineEdit(self.layoutWidget)
        self.portnum.setObjectName("portnum")
        self.gridLayout.addWidget(self.portnum, 1, 1, 1, 2)
        self.textmode = QtGui.QCheckBox(self.layoutWidget)
        self.textmode.setObjectName("textmode")
        self.gridLayout.addWidget(self.textmode, 1, 4, 1, 2)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.username = QtGui.QLineEdit(self.layoutWidget)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 2, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.password = QtGui.QLineEdit(self.layoutWidget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.directory = QtGui.QLineEdit(self.layoutWidget)
        self.directory.setObjectName("directory")
        self.gridLayout.addWidget(self.directory, 3, 1, 1, 5)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.filename = QtGui.QLineEdit(self.layoutWidget)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 4, 1, 1, 5)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.selectto = QtGui.QSpinBox(self.layoutWidget)
        self.selectto.setMinimum(1)
        self.selectto.setMaximum(3600000)
        self.selectto.setSingleStep(10)
        self.selectto.setProperty("value", QtCore.QVariant(750))
        self.selectto.setObjectName("selectto")
        self.gridLayout.addWidget(self.selectto, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 2)
        self.mainto = QtGui.QSpinBox(self.layoutWidget)
        self.mainto.setMinimum(1)
        self.mainto.setMaximum(3600000)
        self.mainto.setSingleStep(100)
        self.mainto.setProperty("value", QtCore.QVariant(30000))
        self.mainto.setObjectName("mainto")
        self.gridLayout.addWidget(self.mainto, 5, 5, 1, 1)
        self.goback = QtGui.QPushButton(ftpparams)
        self.goback.setGeometry(QtCore.QRect(580, 100, 81, 41))
        self.goback.setObjectName("goback")
        self.label_3.setBuddy(self.outhost)
        self.label_4.setBuddy(self.portnum)
        self.label_2.setBuddy(self.username)
        self.label_7.setBuddy(self.password)
        self.label_5.setBuddy(self.directory)
        self.label_6.setBuddy(self.filename)
        self.label_8.setBuddy(self.selectto)
        self.label_9.setBuddy(self.mainto)

        self.retranslateUi(ftpparams)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ftpparams.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ftpparams.reject)
        QtCore.QMetaObject.connectSlotsByName(ftpparams)
        ftpparams.setTabOrder(self.outhost, self.portnum)
        ftpparams.setTabOrder(self.portnum, self.textmode)
        ftpparams.setTabOrder(self.textmode, self.username)
        ftpparams.setTabOrder(self.username, self.password)
        ftpparams.setTabOrder(self.password, self.directory)
        ftpparams.setTabOrder(self.directory, self.filename)
        ftpparams.setTabOrder(self.filename, self.selectto)
        ftpparams.setTabOrder(self.selectto, self.mainto)
        ftpparams.setTabOrder(self.mainto, self.buttonBox)

    def retranslateUi(self, ftpparams):
        ftpparams.setWindowTitle(QtGui.QApplication.translate("ftpparams", "FTP specific parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ftpparams", "&Outgoing host/IP", None, QtGui.QApplication.UnicodeUTF8))
        self.outhost.setToolTip(QtGui.QApplication.translate("ftpparams", "Some network setups may require the sending host to use a specific IP address or host name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ftpparams", "FTP &Control Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portnum.setToolTip(QtGui.QApplication.translate("ftpparams", "This is the port number (or name) to use for the FTP control port\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.portnum.setText(QtGui.QApplication.translate("ftpparams", "ftp", None, QtGui.QApplication.UnicodeUTF8))
        self.textmode.setToolTip(QtGui.QApplication.translate("ftpparams", "Select this to force text mode (not recommended)\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.textmode.setText(QtGui.QApplication.translate("ftpparams", "Force text Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ftpparams", "&User Name", None, QtGui.QApplication.UnicodeUTF8))
        self.username.setToolTip(QtGui.QApplication.translate("ftpparams", "This is the User Name which the server may expect you to log in with\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ftpparams", "&Password", None, QtGui.QApplication.UnicodeUTF8))
        self.password.setToolTip(QtGui.QApplication.translate("ftpparams", "This is the password which the server may expect you to quote", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ftpparams", "Server &Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.directory.setToolTip(QtGui.QApplication.translate("ftpparams", "This is the server \"directory\" which you may be expected to select.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ftpparams", "&File name", None, QtGui.QApplication.UnicodeUTF8))
        self.filename.setToolTip(QtGui.QApplication.translate("ftpparams", "This is the server \"filename\" you may be expected to quote.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ftpparams", "&Select Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.selectto.setToolTip(QtGui.QApplication.translate("ftpparams", "Timeout for \"select\" operations", None, QtGui.QApplication.UnicodeUTF8))
        self.selectto.setSuffix(QtGui.QApplication.translate("ftpparams", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ftpparams", "&Main Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.mainto.setToolTip(QtGui.QApplication.translate("ftpparams", "Main timeout for FTP operations", None, QtGui.QApplication.UnicodeUTF8))
        self.mainto.setSuffix(QtGui.QApplication.translate("ftpparams", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.goback.setToolTip(QtGui.QApplication.translate("ftpparams", "Click here to go back", None, QtGui.QApplication.UnicodeUTF8))
        self.goback.setText(QtGui.QApplication.translate("ftpparams", "Go Back", None, QtGui.QApplication.UnicodeUTF8))

