# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hpnpfparams.ui'
#
# Created: Fri Mar  5 10:14:50 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_hpnpfparams(object):
    def setupUi(self, hpnpfparams):
        hpnpfparams.setObjectName("hpnpfparams")
        hpnpfparams.resize(682, 259)
        self.buttonBox = QtGui.QDialogButtonBox(hpnpfparams)
        self.buttonBox.setGeometry(QtCore.QRect(560, 30, 81, 181))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(hpnpfparams)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 509, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.outhost = QtGui.QLineEdit(self.layoutWidget)
        self.outhost.setObjectName("outhost")
        self.gridLayout.addWidget(self.outhost, 0, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.dataport = QtGui.QLineEdit(self.layoutWidget)
        self.dataport.setObjectName("dataport")
        self.gridLayout.addWidget(self.dataport, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.snmpport = QtGui.QLineEdit(self.layoutWidget)
        self.snmpport.setObjectName("snmpport")
        self.gridLayout.addWidget(self.snmpport, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.defsfile = QtGui.QLineEdit(self.layoutWidget)
        self.defsfile.setObjectName("defsfile")
        self.gridLayout.addWidget(self.defsfile, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.ctrlfile = QtGui.QLineEdit(self.layoutWidget)
        self.ctrlfile.setObjectName("ctrlfile")
        self.gridLayout.addWidget(self.ctrlfile, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.community = QtGui.QLineEdit(self.layoutWidget)
        self.community.setObjectName("community")
        self.gridLayout.addWidget(self.community, 3, 1, 1, 1)
        self.getnext = QtGui.QCheckBox(self.layoutWidget)
        self.getnext.setObjectName("getnext")
        self.gridLayout.addWidget(self.getnext, 3, 2, 1, 2)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.timeout = QtGui.QSpinBox(self.layoutWidget)
        self.timeout.setMaximum(3600000)
        self.timeout.setSingleStep(100)
        self.timeout.setProperty("value", 1000)
        self.timeout.setObjectName("timeout")
        self.gridLayout.addWidget(self.timeout, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.blocksize = QtGui.QSpinBox(self.layoutWidget)
        self.blocksize.setMinimum(1)
        self.blocksize.setMaximum(1024)
        self.blocksize.setProperty("value", 10)
        self.blocksize.setObjectName("blocksize")
        self.gridLayout.addWidget(self.blocksize, 4, 3, 1, 1)
        self.goback = QtGui.QPushButton(hpnpfparams)
        self.goback.setGeometry(QtCore.QRect(560, 120, 81, 41))
        self.goback.setObjectName("goback")
        self.label_3.setBuddy(self.outhost)
        self.label_4.setBuddy(self.dataport)
        self.label_10.setBuddy(self.snmpport)
        self.label_2.setBuddy(self.defsfile)
        self.label_7.setBuddy(self.ctrlfile)
        self.label_5.setBuddy(self.community)
        self.label_6.setBuddy(self.timeout)
        self.label_8.setBuddy(self.blocksize)

        self.retranslateUi(hpnpfparams)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), hpnpfparams.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), hpnpfparams.reject)
        QtCore.QMetaObject.connectSlotsByName(hpnpfparams)
        hpnpfparams.setTabOrder(self.outhost, self.dataport)
        hpnpfparams.setTabOrder(self.dataport, self.snmpport)
        hpnpfparams.setTabOrder(self.snmpport, self.defsfile)
        hpnpfparams.setTabOrder(self.defsfile, self.ctrlfile)
        hpnpfparams.setTabOrder(self.ctrlfile, self.community)
        hpnpfparams.setTabOrder(self.community, self.getnext)
        hpnpfparams.setTabOrder(self.getnext, self.timeout)
        hpnpfparams.setTabOrder(self.timeout, self.blocksize)
        hpnpfparams.setTabOrder(self.blocksize, self.buttonBox)
        hpnpfparams.setTabOrder(self.buttonBox, self.goback)

    def retranslateUi(self, hpnpfparams):
        hpnpfparams.setWindowTitle(QtGui.QApplication.translate("hpnpfparams", "HPNPF specific parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("hpnpfparams", "&Outgoing host/IP", None, QtGui.QApplication.UnicodeUTF8))
        self.outhost.setToolTip(QtGui.QApplication.translate("hpnpfparams", "Some network setups may require the sending host to use a specific IP address or host name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("hpnpfparams", "&Data Port", None, QtGui.QApplication.UnicodeUTF8))
        self.dataport.setToolTip(QtGui.QApplication.translate("hpnpfparams", "This is the port number (or name) to use for the data", None, QtGui.QApplication.UnicodeUTF8))
        self.dataport.setText(QtGui.QApplication.translate("hpnpfparams", "9100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("hpnpfparams", "&SNMP Port", None, QtGui.QApplication.UnicodeUTF8))
        self.snmpport.setToolTip(QtGui.QApplication.translate("hpnpfparams", "This is the port number (or name) to use for the SNMP comms port", None, QtGui.QApplication.UnicodeUTF8))
        self.snmpport.setText(QtGui.QApplication.translate("hpnpfparams", "snmp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("hpnpfparams", "De&fs file", None, QtGui.QApplication.UnicodeUTF8))
        self.defsfile.setToolTip(QtGui.QApplication.translate("hpnpfparams", "This file is used to supply macro names for SNMP variables", None, QtGui.QApplication.UnicodeUTF8))
        self.defsfile.setText(QtGui.QApplication.translate("hpnpfparams", "SDATADIR/xtsnmpdef", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("hpnpfparams", "&Control file", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrlfile.setToolTip(QtGui.QApplication.translate("hpnpfparams", "This file is the SNMP operations control file", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrlfile.setText(QtGui.QApplication.translate("hpnpfparams", "SDATADIR/xtlhp-ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("hpnpfparams", "Co&mmunity", None, QtGui.QApplication.UnicodeUTF8))
        self.community.setToolTip(QtGui.QApplication.translate("hpnpfparams", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Community name for SNMP operations usually <span style=\" font-style:italic;\">public</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.community.setText(QtGui.QApplication.translate("hpnpfparams", "public", None, QtGui.QApplication.UnicodeUTF8))
        self.getnext.setToolTip(QtGui.QApplication.translate("hpnpfparams", "Use get next operation when fetching SNMP vars", None, QtGui.QApplication.UnicodeUTF8))
        self.getnext.setText(QtGui.QApplication.translate("hpnpfparams", "&Get next var", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("hpnpfparams", "&Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.timeout.setToolTip(QtGui.QApplication.translate("hpnpfparams", "Timeout for operations (milliseconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeout.setSuffix(QtGui.QApplication.translate("hpnpfparams", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("hpnpfparams", "&Blocksize", None, QtGui.QApplication.UnicodeUTF8))
        self.blocksize.setToolTip(QtGui.QApplication.translate("hpnpfparams", "Data blocksize, SNMP enquiry in between blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.blocksize.setSuffix(QtGui.QApplication.translate("hpnpfparams", " KB", None, QtGui.QApplication.UnicodeUTF8))
        self.goback.setToolTip(QtGui.QApplication.translate("hpnpfparams", "Click here to go back", None, QtGui.QApplication.UnicodeUTF8))
        self.goback.setText(QtGui.QApplication.translate("hpnpfparams", "Go Back", None, QtGui.QApplication.UnicodeUTF8))

