# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'netparams.ui'
#
# Created: Sat Jul  3 23:26:42 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_netparams(object):
    def setupUi(self, netparams):
        netparams.setObjectName("netparams")
        netparams.resize(458, 365)
        self.buttonBox = QtGui.QDialogButtonBox(netparams)
        self.buttonBox.setGeometry(QtCore.QRect(350, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(netparams)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 20, 299, 314))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.opento = QtGui.QSpinBox(self.layoutWidget)
        self.opento.setMaximum(65535)
        self.opento.setProperty("value", 30)
        self.opento.setObjectName("opento")
        self.gridLayout.addWidget(self.opento, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.offlineto = QtGui.QSpinBox(self.layoutWidget)
        self.offlineto.setMaximum(65535)
        self.offlineto.setProperty("value", 300)
        self.offlineto.setObjectName("offlineto")
        self.gridLayout.addWidget(self.offlineto, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.closeto = QtGui.QSpinBox(self.layoutWidget)
        self.closeto.setMaximum(65535)
        self.closeto.setProperty("value", 10000)
        self.closeto.setObjectName("closeto")
        self.gridLayout.addWidget(self.closeto, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.outbuffer = QtGui.QSpinBox(self.layoutWidget)
        self.outbuffer.setMinimum(1)
        self.outbuffer.setMaximum(1048576)
        self.outbuffer.setSingleStep(1024)
        self.outbuffer.setProperty("value", 1024)
        self.outbuffer.setObjectName("outbuffer")
        self.gridLayout.addWidget(self.outbuffer, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.postclose = QtGui.QSpinBox(self.layoutWidget)
        self.postclose.setMaximum(3600)
        self.postclose.setObjectName("postclose")
        self.gridLayout.addWidget(self.postclose, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.canhang = QtGui.QCheckBox(self.layoutWidget)
        self.canhang.setObjectName("canhang")
        self.gridLayout.addWidget(self.canhang, 5, 0, 1, 3)
        self.reopen = QtGui.QCheckBox(self.layoutWidget)
        self.reopen.setChecked(True)
        self.reopen.setObjectName("reopen")
        self.gridLayout.addWidget(self.reopen, 6, 0, 1, 3)
        self.logerror = QtGui.QCheckBox(self.layoutWidget)
        self.logerror.setChecked(True)
        self.logerror.setObjectName("logerror")
        self.gridLayout.addWidget(self.logerror, 7, 0, 1, 3)
        self.fberror = QtGui.QCheckBox(self.layoutWidget)
        self.fberror.setChecked(True)
        self.fberror.setObjectName("fberror")
        self.gridLayout.addWidget(self.fberror, 8, 0, 1, 3)
        self.label_3.setBuddy(self.opento)
        self.label_4.setBuddy(self.offlineto)
        self.label.setBuddy(self.closeto)
        self.label_5.setBuddy(self.outbuffer)
        self.label_2.setBuddy(self.postclose)

        self.retranslateUi(netparams)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), netparams.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), netparams.reject)
        QtCore.QMetaObject.connectSlotsByName(netparams)
        netparams.setTabOrder(self.opento, self.offlineto)
        netparams.setTabOrder(self.offlineto, self.closeto)
        netparams.setTabOrder(self.closeto, self.outbuffer)
        netparams.setTabOrder(self.outbuffer, self.postclose)
        netparams.setTabOrder(self.postclose, self.canhang)
        netparams.setTabOrder(self.canhang, self.reopen)
        netparams.setTabOrder(self.reopen, self.logerror)
        netparams.setTabOrder(self.logerror, self.fberror)
        netparams.setTabOrder(self.fberror, self.buttonBox)

    def retranslateUi(self, netparams):
        netparams.setWindowTitle(QtGui.QApplication.translate("netparams", "Network parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("netparams", "Open &Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.opento.setToolTip(QtGui.QApplication.translate("netparams", "Timeout trying to open port before deciding it\'s offline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("netparams", "Offline &Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.offlineto.setToolTip(QtGui.QApplication.translate("netparams", "Timeout when trying to write to device before deciding it\'s offline", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("netparams", "&Close Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.closeto.setToolTip(QtGui.QApplication.translate("netparams", "Time to wait for port close to occur before considering it offline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("netparams", "&Output buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.outbuffer.setToolTip(QtGui.QApplication.translate("netparams", "Output buffer size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("netparams", "&Postclose", None, QtGui.QApplication.UnicodeUTF8))
        self.postclose.setToolTip(QtGui.QApplication.translate("netparams", "Wait this number of seconds after each job before starting anything else", None, QtGui.QApplication.UnicodeUTF8))
        self.canhang.setToolTip(QtGui.QApplication.translate("netparams", "Try to avoid system hangup when devices locked", None, QtGui.QApplication.UnicodeUTF8))
        self.canhang.setText(QtGui.QApplication.translate("netparams", "\"Hang\" avoidance", None, QtGui.QApplication.UnicodeUTF8))
        self.reopen.setToolTip(QtGui.QApplication.translate("netparams", "Close and reopen device after each job", None, QtGui.QApplication.UnicodeUTF8))
        self.reopen.setText(QtGui.QApplication.translate("netparams", "Reopen", None, QtGui.QApplication.UnicodeUTF8))
        self.logerror.setToolTip(QtGui.QApplication.translate("netparams", "Copy error messages to system log file", None, QtGui.QApplication.UnicodeUTF8))
        self.logerror.setText(QtGui.QApplication.translate("netparams", "&Log errors", None, QtGui.QApplication.UnicodeUTF8))
        self.fberror.setToolTip(QtGui.QApplication.translate("netparams", "Display last error message on queue monitor screen", None, QtGui.QApplication.UnicodeUTF8))
        self.fberror.setText(QtGui.QApplication.translate("netparams", "&Feedback errors", None, QtGui.QApplication.UnicodeUTF8))

