# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ptrinstall_main.ui'
#
# Created: Sat Jul  3 23:26:45 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 452)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 801, 431))
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Create = QtGui.QMenu(self.menubar)
        self.menu_Create.setObjectName("menu_Create")
        self.menu_Remove = QtGui.QMenu(self.menubar)
        self.menu_Remove.setObjectName("menu_Remove")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.action_Quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon)
        self.action_Quit.setObjectName("action_Quit")
        self.action_new = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("newptr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new.setIcon(icon1)
        self.action_new.setObjectName("action_new")
        self.action_About_ptrinstall = QtGui.QAction(MainWindow)
        self.action_About_ptrinstall.setObjectName("action_About_ptrinstall")
        self.action_clone = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("clone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clone.setIcon(icon2)
        self.action_clone.setObjectName("action_clone")
        self.action_install = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("install.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_install.setIcon(icon3)
        self.action_install.setObjectName("action_install")
        self.action_uninstall = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("uninstall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_uninstall.setIcon(icon4)
        self.action_uninstall.setObjectName("action_uninstall")
        self.action_deldef = QtGui.QAction(MainWindow)
        self.action_deldef.setObjectName("action_deldef")
        self.action_edit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("device.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_edit.setIcon(icon5)
        self.action_edit.setObjectName("action_edit")
        self.action_editspool = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("options.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_editspool.setIcon(icon6)
        self.action_editspool.setObjectName("action_editspool")
        self.action_setptrtype = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ptrtype.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setptrtype.setIcon(icon7)
        self.action_setptrtype.setObjectName("action_setptrtype")
        self.menu_File.addAction(self.action_Quit)
        self.menu_Create.addAction(self.action_new)
        self.menu_Create.addAction(self.action_clone)
        self.menu_Create.addAction(self.action_edit)
        self.menu_Create.addAction(self.action_setptrtype)
        self.menu_Create.addAction(self.action_editspool)
        self.menu_Create.addSeparator()
        self.menu_Create.addAction(self.action_install)
        self.menu_Remove.addAction(self.action_uninstall)
        self.menu_Remove.addSeparator()
        self.menu_Remove.addAction(self.action_deldef)
        self.menu_Help.addAction(self.action_About_ptrinstall)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Create.menuAction())
        self.menubar.addAction(self.menu_Remove.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_new)
        self.toolBar.addAction(self.action_clone)
        self.toolBar.addAction(self.action_edit)
        self.toolBar.addAction(self.action_setptrtype)
        self.toolBar.addAction(self.action_editspool)
        self.toolBar.addAction(self.action_install)
        self.toolBar.addAction(self.action_uninstall)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Manage printer definitions", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Create.setTitle(QtGui.QApplication.translate("MainWindow", "&Create", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Remove.setTitle(QtGui.QApplication.translate("MainWindow", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setText(QtGui.QApplication.translate("MainWindow", "&New printer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_ptrinstall.setText(QtGui.QApplication.translate("MainWindow", "&About Ptrinstall", None, QtGui.QApplication.UnicodeUTF8))
        self.action_clone.setText(QtGui.QApplication.translate("MainWindow", "&Clone existing printer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_install.setText(QtGui.QApplication.translate("MainWindow", "&Install printer to system", None, QtGui.QApplication.UnicodeUTF8))
        self.action_uninstall.setText(QtGui.QApplication.translate("MainWindow", "&Uninstall printer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_deldef.setText(QtGui.QApplication.translate("MainWindow", "Delete definition", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit.setText(QtGui.QApplication.translate("MainWindow", "&Edit printer device definition", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit.setIconText(QtGui.QApplication.translate("MainWindow", "Edit printer device definition", None, QtGui.QApplication.UnicodeUTF8))
        self.action_edit.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit printer definition (not appropriate for clones)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_editspool.setText(QtGui.QApplication.translate("MainWindow", "Edit spooler options", None, QtGui.QApplication.UnicodeUTF8))
        self.action_editspool.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit the spooler options, e.g. header force on/off", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setptrtype.setText(QtGui.QApplication.translate("MainWindow", "Set printer &type", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setptrtype.setToolTip(QtGui.QApplication.translate("MainWindow", "Set printer type and emulation.", None, QtGui.QApplication.UnicodeUTF8))

