# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serialparams.ui'
#
# Created: Sat Jul  3 23:26:43 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_serialparams(object):
    def setupUi(self, serialparams):
        serialparams.setObjectName("serialparams")
        serialparams.resize(433, 517)
        self.buttonBox = QtGui.QDialogButtonBox(serialparams)
        self.buttonBox.setGeometry(QtCore.QRect(330, 10, 81, 91))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(serialparams)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 263, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.baudrate = QtGui.QComboBox(self.layoutWidget)
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.gridLayout.addWidget(self.baudrate, 0, 1, 1, 3)
        self.xon = QtGui.QCheckBox(self.layoutWidget)
        self.xon.setChecked(True)
        self.xon.setObjectName("xon")
        self.gridLayout.addWidget(self.xon, 1, 0, 1, 4)
        self.xany = QtGui.QCheckBox(self.layoutWidget)
        self.xany.setObjectName("xany")
        self.gridLayout.addWidget(self.xany, 2, 0, 1, 4)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.csize = QtGui.QComboBox(self.layoutWidget)
        self.csize.setObjectName("csize")
        self.csize.addItem("")
        self.csize.addItem("")
        self.csize.addItem("")
        self.csize.addItem("")
        self.gridLayout.addWidget(self.csize, 3, 2, 1, 2)
        self.twostop = QtGui.QCheckBox(self.layoutWidget)
        self.twostop.setObjectName("twostop")
        self.gridLayout.addWidget(self.twostop, 4, 0, 1, 2)
        self.parity = QtGui.QComboBox(self.layoutWidget)
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.gridLayout.addWidget(self.parity, 4, 3, 1, 1)
        self.clocal = QtGui.QCheckBox(self.layoutWidget)
        self.clocal.setObjectName("clocal")
        self.gridLayout.addWidget(self.clocal, 5, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 2)
        self.opento = QtGui.QSpinBox(self.layoutWidget)
        self.opento.setMaximum(65535)
        self.opento.setProperty("value", 30)
        self.opento.setObjectName("opento")
        self.gridLayout.addWidget(self.opento, 6, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.offlineto = QtGui.QSpinBox(self.layoutWidget)
        self.offlineto.setMaximum(65535)
        self.offlineto.setProperty("value", 300)
        self.offlineto.setObjectName("offlineto")
        self.gridLayout.addWidget(self.offlineto, 7, 2, 1, 2)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 2)
        self.outbuffer = QtGui.QSpinBox(self.layoutWidget)
        self.outbuffer.setMinimum(1)
        self.outbuffer.setMaximum(1048576)
        self.outbuffer.setSingleStep(1024)
        self.outbuffer.setProperty("value", 1024)
        self.outbuffer.setObjectName("outbuffer")
        self.gridLayout.addWidget(self.outbuffer, 8, 2, 1, 2)
        self.canhang = QtGui.QCheckBox(self.layoutWidget)
        self.canhang.setObjectName("canhang")
        self.gridLayout.addWidget(self.canhang, 9, 0, 1, 4)
        self.reopen = QtGui.QCheckBox(self.layoutWidget)
        self.reopen.setObjectName("reopen")
        self.gridLayout.addWidget(self.reopen, 10, 0, 1, 2)
        self.onlcr = QtGui.QCheckBox(self.layoutWidget)
        self.onlcr.setObjectName("onlcr")
        self.gridLayout.addWidget(self.onlcr, 11, 0, 1, 2)
        self.label.setBuddy(self.baudrate)
        self.label_2.setBuddy(self.csize)
        self.label_3.setBuddy(self.opento)
        self.label_4.setBuddy(self.offlineto)
        self.label_5.setBuddy(self.outbuffer)

        self.retranslateUi(serialparams)
        self.baudrate.setCurrentIndex(4)
        self.csize.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), serialparams.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), serialparams.reject)
        QtCore.QMetaObject.connectSlotsByName(serialparams)
        serialparams.setTabOrder(self.baudrate, self.xon)
        serialparams.setTabOrder(self.xon, self.xany)
        serialparams.setTabOrder(self.xany, self.csize)
        serialparams.setTabOrder(self.csize, self.twostop)
        serialparams.setTabOrder(self.twostop, self.parity)
        serialparams.setTabOrder(self.parity, self.clocal)
        serialparams.setTabOrder(self.clocal, self.opento)
        serialparams.setTabOrder(self.opento, self.offlineto)
        serialparams.setTabOrder(self.offlineto, self.outbuffer)
        serialparams.setTabOrder(self.outbuffer, self.canhang)
        serialparams.setTabOrder(self.canhang, self.reopen)
        serialparams.setTabOrder(self.reopen, self.onlcr)
        serialparams.setTabOrder(self.onlcr, self.buttonBox)

    def retranslateUi(self, serialparams):
        serialparams.setWindowTitle(QtGui.QApplication.translate("serialparams", "Set serial line parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("serialparams", "&Baud Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setToolTip(QtGui.QApplication.translate("serialparams", "This is the serial baud rate to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(0, QtGui.QApplication.translate("serialparams", "1200", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(1, QtGui.QApplication.translate("serialparams", "1800", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(2, QtGui.QApplication.translate("serialparams", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(3, QtGui.QApplication.translate("serialparams", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(4, QtGui.QApplication.translate("serialparams", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(5, QtGui.QApplication.translate("serialparams", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.baudrate.setItemText(6, QtGui.QApplication.translate("serialparams", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.xon.setToolTip(QtGui.QApplication.translate("serialparams", "Select this for x/on-x/off flow control", None, QtGui.QApplication.UnicodeUTF8))
        self.xon.setText(QtGui.QApplication.translate("serialparams", "X/on - X/off flow control", None, QtGui.QApplication.UnicodeUTF8))
        self.xany.setToolTip(QtGui.QApplication.translate("serialparams", "Select this to restart with any character when using X/on-X/off", None, QtGui.QApplication.UnicodeUTF8))
        self.xany.setText(QtGui.QApplication.translate("serialparams", "Any character restart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("serialparams", "Character &Size", None, QtGui.QApplication.UnicodeUTF8))
        self.csize.setToolTip(QtGui.QApplication.translate("serialparams", "Size of each character", None, QtGui.QApplication.UnicodeUTF8))
        self.csize.setItemText(0, QtGui.QApplication.translate("serialparams", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.csize.setItemText(1, QtGui.QApplication.translate("serialparams", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.csize.setItemText(2, QtGui.QApplication.translate("serialparams", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.csize.setItemText(3, QtGui.QApplication.translate("serialparams", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.twostop.setToolTip(QtGui.QApplication.translate("serialparams", "Two stop bits", None, QtGui.QApplication.UnicodeUTF8))
        self.twostop.setText(QtGui.QApplication.translate("serialparams", "&Two stop bits", None, QtGui.QApplication.UnicodeUTF8))
        self.parity.setToolTip(QtGui.QApplication.translate("serialparams", "Whether parity bit and whether odd or even", None, QtGui.QApplication.UnicodeUTF8))
        self.parity.setItemText(0, QtGui.QApplication.translate("serialparams", "No Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.parity.setItemText(1, QtGui.QApplication.translate("serialparams", "Even Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.parity.setItemText(2, QtGui.QApplication.translate("serialparams", "Odd Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.clocal.setToolTip(QtGui.QApplication.translate("serialparams", "Turn off modem control", None, QtGui.QApplication.UnicodeUTF8))
        self.clocal.setText(QtGui.QApplication.translate("serialparams", "No modem control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("serialparams", "Open &Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.opento.setToolTip(QtGui.QApplication.translate("serialparams", "Timeout trying to open serial port before deciding it\'s offline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("serialparams", "Offline &Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.offlineto.setToolTip(QtGui.QApplication.translate("serialparams", "Timeout when trying to write to device before deciding it\'s offline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("serialparams", "&Output buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.outbuffer.setToolTip(QtGui.QApplication.translate("serialparams", "Output buffer size", None, QtGui.QApplication.UnicodeUTF8))
        self.canhang.setToolTip(QtGui.QApplication.translate("serialparams", "Try to avoid system hangup when devices locked", None, QtGui.QApplication.UnicodeUTF8))
        self.canhang.setText(QtGui.QApplication.translate("serialparams", "\"Hang\" avoidance", None, QtGui.QApplication.UnicodeUTF8))
        self.reopen.setToolTip(QtGui.QApplication.translate("serialparams", "Close and reopen device after each job", None, QtGui.QApplication.UnicodeUTF8))
        self.reopen.setText(QtGui.QApplication.translate("serialparams", "Reopen", None, QtGui.QApplication.UnicodeUTF8))
        self.onlcr.setToolTip(QtGui.QApplication.translate("serialparams", "Insert carriage returns before each linefeed (at driver level)", None, QtGui.QApplication.UnicodeUTF8))
        self.onlcr.setText(QtGui.QApplication.translate("serialparams", "Insert CRs", None, QtGui.QApplication.UnicodeUTF8))

