#!/bin/sh
#
#   Copyright 2008 Free Software Foundation, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Host=${SPOOLHOST:-`uname -n | cut -d. -f1`}
e=''
bw=5493
bty=240
bby=1920
date1=`date`

cat - <<EOF
$e&k3G$e&a240v$e(8U$e(s1p60v1s0b16901T
 $SPOOLPUNAME$e(s16v0S

				Request: $SPOOLJOB from $Host

				Title: $SPOOLHDR

EOF
if [ "$SPOOLJUNAME" != "$SPOOLPUNAME" ]
then
    cat - <<EOF
				Submitted by: $SPOOLJUNAME
EOF
fi
cat - <<EOF


  $date1
$e&l0E$e&a${bty}v0H$e*c4h1680v0P$e&a${bty}v0H$e*c${bw}h4v0P$e&a${bby}v0H$e*c${bw}h4v0P$e&a${bty}v${bw}H$e*c4h1680v0P$e&l0e8C$e&a${bty}v0H$e*c${bw}h1680v10g2P${e}E$e%-12345X
EOF

exit 0
