//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sprserv.rc
//
#define IDR_MAINFRAME                   2
#define IDI_NOCONN                      5
#define IDP_XTENQ_PASSREQ               50
#define IDP_XTENQ_BADPASSWD             51
#define IDP_XTENQ_UNKNOWN               52
#define IDP_XTENQ_BADCLIENT             53
#define IDP_XTENQ_UNKNOWNU              54
#define IDP_CONNDIED                    56
#define IDD_ABOUTBOX                    100
#define IDP_NOFILESELECTED              100
#define IDD_DROPPEDFILE                 101
#define IDP_DIRECNOTFOUND               101
#define IDD_FORMDLG                     102
#define IDP_NOTDIR                      102
#define IDD_MESSG                       103
#define IDP_WRONGFORM                   103
#define IDD_MONFILE                     104
#define IDP_BADDELIMITER                104
#define IDD_PAGE                        105
#define IDP_STARTPGENDP                 105
#define IDD_RETAIN                      106
#define IDP_PRINGNPRIN                  106
#define IDD_SECURITY22                  107
#define IDP_ZEROCLASS                   107
#define IDD_SIZELIM                     108
#define IDP_PREVINSTANCE                108
#define IDD_USERMAIL                    109
#define IDP_WRONGPTR                    109
#define IDD_REFRESHCONN                 110
#define IDP_CBINDSOCKET                 112
#define IDS_JANUARY                     113
#define IDS_FEBRUARY                    114
#define IDS_MARCH                       115
#define IDS_APRIL                       116
#define IDS_MAY                         117
#define IDS_JUNE                        118
#define IDS_JULY                        119
#define IDS_AUGUST                      120
#define IDS_SEPTEMBER                   121
#define IDS_OCTOBER                     122
#define IDS_NOVEMBER                    123
#define IDS_DECEMBER                    124
#define IDS_SUNDAY                      125
#define IDS_MONDAY                      126
#define IDS_TUESDAY                     127
#define IDS_WEDNESDAY                   128
#define IDS_THURSDAY                    129
#define IDS_FRIDAY                      130
#define IDS_SATURDAY                    131
#define IDD_LOGINHOST                   132
#define IDD_RETAINABS                   133
#define IDC_MONFILE                     150
#define IDC_SETFORM                     151
#define IDC_POLLTIME                    152
#define IDC_SCR_POLLTIME                153
#define IDC_NOTYET                      154
#define IDC_FORMTYPE                    155
#define IDC_HEADER                      156
#define IDC_SUPPH                       157
#define IDC_PRINTER                     158
#define IDC_COPIES                      159
#define IDC_SCR_COPIES                  160
#define IDC_PRIORITY                    161
#define IDC_SCR_PRIORITY                162
#define IDC_UNIXHOST                    163
#define IDC_CLIENTHOST                  164
#define IDP_NO_SERVER                   164
#define IDC_USER                        165
#define IDC_PASSWD                      166
#define IDC_FROMHOST                    167
#define IDC_MESSAGE                     168
#define IDC_STARTP                      169
#define IDC_SCR_STARTP                  170
#define IDC_ENDP                        171
#define IDC_SCR_ENDP                    172
#define IDC_ALLP                        173
#define IDC_ODDP                        174
#define IDC_EVENP                       175
#define IDC_SWAPOE                      176
#define IDC_DELIMNUM                    177
#define IDC_SCR_DELIMNUM                178
#define IDC_DELIMITER                   179
#define IDC_PPFLAGS                     180
#define IDC_RETAIN                      181
#define IDC_DIP                         182
#define IDC_SCR_DIP                     183
#define IDC_DINP                        184
#define IDC_SCR_DINP                    185
#define IDC_HOLD                        186
#define IDC_HOUR                        187
#define IDC_MIN                         188
#define IDC_WDAY                        189
#define IDC_MDAY                        190
#define IDC_MON                         191
#define IDC_SCR_HOUR                    192
#define IDC_SCR_MIN                     193
#define IDC_SCR_WDAY                    194
#define IDC_SCR_MDAY                    195
#define IDC_SCR_MON                     196
#define IDC_COLON                       197
#define IDC_SETALL                      198
#define IDC_CLEARALL                    199
#define IDC_CC_A                        200
#define IDP_NO_HOSTFILE                 200
#define IDC_CC_B                        201
#define IDP_HF_INVALIDHOST              201
#define IDC_COLON2                      201
#define IDC_CC_C                        202
#define IDP_HF_BADTIMEOUT               202
#define IDC_COLON3                      202
#define IDC_CC_D                        203
#define IDP_HF_NOALIAS                  203
#define IDC_CC_E                        204
#define IDC_CC_F                        205
#define IDC_CC_G                        206
#define IDP_GSPU_NOSOCK                 206
#define IDC_CC_H                        207
#define IDP_GSPU_NOBIND                 207
#define IDC_CC_I                        208
#define IDP_GSPU_NOSEND                 208
#define IDC_CC_J                        209
#define IDP_GSPU_NORECV                 209
#define IDC_CC_K                        210
#define IDP_GSPU_NVALID                 210
#define IDC_CC_L                        211
#define IDP_JSENDFAIL                   211
#define IDC_CC_M                        212
#define IDP_JRECVFAIL                   212
#define IDC_CC_N                        213
#define IDP_CCOUTSOCKET                 213
#define IDC_CC_O                        214
#define IDP_REJECTED                    214
#define IDC_CC_P                        215
#define IDP_REJ_NOTCLIENT               215
#define IDC_CC_A2                       216
#define IDP_REJ_NOTUSER                 216
#define IDC_CC_B2                       217
#define IDP_REJ_ZEROCLASS               217
#define IDC_CC_C2                       218
#define IDP_REJ_BADPRIO                 218
#define IDC_CC_D2                       219
#define IDP_REJ_BADCOPIES               219
#define IDC_CC_E2                       220
#define IDP_REJ_BADFORM                 220
#define IDC_CC_F2                       221
#define IDP_REJ_NOMEM                   221
#define IDC_CC_G2                       222
#define IDP_REJ_BADPAGE                 222
#define IDC_CC_H2                       223
#define IDP_REJ_NOMEMPF                 223
#define IDC_CC_I2                       224
#define IDP_REJ_CCPAGEFILE              224
#define IDC_CC_J2                       225
#define IDP_REJ_FULL                    225
#define IDC_CC_K2                       226
#define IDP_REJ_QFULL                   226
#define IDC_CC_L2                       227
#define IDP_REJ_EMPTYFILE               227
#define IDC_CC_M2                       228
#define IDP_REJ_BADPTR                  228
#define IDC_CC_N2                       229
#define IDP_WARNLIMIT                   229
#define IDC_CC_O2                       230
#define IDP_REJ_ERRLIMIT                230
#define IDC_CC_P2                       231
#define IDC_LOCALONLY                   232
#define IDP_FILETOOBIG                  232
#define IDC_LIMIT                       233
#define IDP_NOTSAVEDJOB                 233
#define IDC_SCR_LIMIT                   234
#define IDP_CANNOTOPENFILE              234
#define IDC_LIMITK                      235
#define IDP_SJINVALIDCPS                235
#define IDC_LIMITP                      236
#define IDP_SJINVALIDCC                 236
#define IDC_ERRLIMIT                    237
#define IDP_SJINVALIDPRIO               237
#define IDC_MAIL                        238
#define IDP_SJINVALIDRANGE              238
#define IDC_WRITE                       239
#define IDP_SJINVALIDTIMEOUT            239
#define IDC_MATTN                       240
#define IDP_SJINVALIDHOLD               240
#define IDC_WATTN                       241
#define IDP_SJINVALIDDELIM              241
#define IDP_SJINVALIDOE                 242
#define IDC_SERVNAME                    242
#define IDP_SJINVALIDARG                243
#define IDC_REFRESHCONN                 243
#define IDP_SJMISSARG                   244
#define IDC_REFRDONTASK                 244
#define IDP_CANTOPENJOBFILE             245
#define IDC_TERMINATE                   245
#define IDP_OKTOSUBMIT                  246
#define IDC_DELHOURS                    246
#define IDP_SK_CCMSGSOCK                247
#define IDC_DELMINS                     247
#define IDP_MSGASYNCSEL                 248
#define IDC_DELSECS                     248
#define IDP_NOMSGFILE                   249
#define IDC_SCR_DELHOURS                249
#define IDP_NOCMDFILES                  250
#define IDC_SCR_DELMINS                 250
#define IDC_SCR_DELSECS                 251
#define ID_LIST_ADDNEWFILE              32768
#define ID_LIST_DELETEFILEFROMLIST      32769
#define ID_LIST_CHANGEFILENAME          32770
#define ID_LIST_SELECTDEFAULTDIRECTORY  32771
#define ID_OPTIONS_RESTOREDEFAULTS      32772
#define ID_OPTIONS_FORMHEADERCOPIES     32773
#define ID_OPTIONS_USERANDMAIL          32774
#define ID_OPTIONS_PAGE                 32775
#define ID_OPTIONS_RETAIN               32776
#define ID_OPTIONS_SECURITY             32777
#define ID_LIST_FORMHEADERCOPIES        32778
#define ID_LIST_USERANDMAIL             32779
#define ID_LIST_PAGE                    32780
#define ID_LIST_RETAIN                  32781
#define ID_LIST_SECURITY                32782
#define ID_LIST_OK                      32783
#define ID_LIST_WRITETOWININI           32784
#define ID_OPTIONS_SIZELIMIT            32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         250
#define _APS_NEXT_SYMED_VALUE           133
#endif
#endif
