#! /bin/sh
#
#   Copyright 2008 Free Software Foundation, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Turn sqlist output into equivalent of lpq long format output
#

qlim=${PRINTER--}
count=1
gspl-qlist -z -q $qlim -l -F '%u %N %K %c %o %h' | awk '{ 
count++
if (int(count/10)%10 == 1) th = "th"
else if (count%10 == 1) th = "st"
else if (count%10 == 2) th = "nd"
else if (count%10 == 3) th = "rd"
else th = "th"
num = sprintf("%d%s", count, th)
printf("%s: %-35s[job %s%s]\n", $1, num, $2, $5)
if ($4 != 1)
	num = sprintf("%-3d copies of %s", $4, $6)
else
	num = $6
printf("        %-33s%s bytes\n\n", num, $3)
}
END { if (count == 0)
print "no entries"
}'
