=head1 NAME

gnuspool.conf - master configuration file

=head1 DESCRIPTION

F<gnuspool.conf> is an optional file for providing additional
environment variables to component programs of the B<GNUspool> spooler
and document management system.

This may be useful for relocating standard files and directories, such
as B<SPOOLDIR>, so that a different spool directory is used.

However completely arbitrary environment variable assignments may be
made, in particular so as to pass the resulting environment on to
subprocesses invoked by the despooler program spd(8).

The format of the file consists of environment variable assignments
such as:

	SPOOLDIR=/usr2/spooldir

Comment lines may be included, introduced by a B<#> sign and blank
lines are ignored.

Every component program of B<GNUspool> examines this file and resets
its environment from this file as the first step of execution.

=head1 IMPORTANT NOTES

=over 4

=item 1

Make sure that F<gnuspool.conf> is world-readable!

=item 2

Ensure that no part of B<GNUspool> is running before altering this
file.

=back

=head1 FILES

F<gnuspool.conf>
master configuration file

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: auto-fill
## End:
