=head1 NAME

gsl-mpr - print spooler or save if not running

gspl-mrpr - print spooler to remote queue or save if unavailable

=head1 SYNOPSIS

B<gsl-mpr>
[ I<-options> ]
[ I<file> ... ]

B<gspl-mrpr>
[ I<-options> ]
[ I<file> ... ]

=head1 DESCRIPTION

B<gsl-mpr> either queues up one or more print jobs for the B<GNUspool>
spooler using gspl-pr(1) if it is running, or else places a series of
files in an alternative spool directory, such that when run as shell
scripts when the B<GNUspool> spooler process spshed(8) is running, the
jobs are queued as originally specified.

B<gspl-mrpr> queues up one or more print jobs to a remote queue running
the B<GNUspool> spooler using gspl-rpr(1) if it is available, or otherwise
places a series of files in an alternative spool directory for
queueing when the remote machine is available.

=head1 OPTIONS

Options are as per B<gspl-pr> and B<gspl-rpr>. If the job can be queued
immediately, these programs are directly invoked.

=head1 EXIT CODES

An exit code of zero is returned if the job or jobs are successfully
queued using gspl-pr(1) or gspl-rpr(1) or successfully saved in the alternate
directory. Any non-zero exit code from gspl-pr(1) or gspl-rpr(1) will be
passed back to the user. Standard exit codes and error messages are
displayed if the files cannot be opened or saved.

=head1 FILES

F<~/.gnuspool>
configuration file (home directory)

F< .gnuspool>
configuration file (current directory)

F<rest.help>
message file

F<gnuspool_alt/CMDF*>
command file (shell script)

F<gnuspool_alt/ASPF*>
data file (contents of job)

=head1 ENVIRONMENT

=over 4

=item GSPL_PR

space-separated options to override defaults for B<gspl-pr>.

=item GSPL_RPR

space-separated options to override defaults for B<gspl-mrpr>.

=item SPRESTCONF

location of alternative help file.

=item ALTSPD

location of alternate spool directory.

=back

=head1 SEE ALSO

gnuspool.conf(5),
gnuspool.hosts(5),
gspl-rpr(1)
gspl-pr(1),
spsyntax(5),
spshed(8),
xtnetserv(8).

=head1 DIAGNOSTICS

Various diagnostics are read and printed as required from the message
file, by default F<rest.help>.

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
