=head1 NAME

gspl-lprm - delete jobs on LPD protocol servers

=head1 SYNOPSIS

B<gspl-lprm>
I<printer>
I<job> ...

=head1 DESCRIPTION

B<gspl-lprm> deletes pending jobs on an external
print server supporting the LPD protocol.

=head1 OPTIONS

Note that the order of treatment, letters and keywords described below
may be modified by editing the file F<splpd.help> -
see spsyntax(5).

The environment variable on which options are supplied is C<GSPL_LPRM> and the
environment variable to specify the help file is C<LPDINTCONF>.

=over 4

=item -? or +explain

Causes a summary of the other options to be displayed without taking
further action.

=item +freeze-current

Save all the current options in a F<.gnuspool> file in the current
directory.

=item +freeze-home

Save all the current options in a F<.gnuspool> file in the user's home
directory.

=back

=head1 FILES

F<~/.gnuspool>
configuration file (home directory)

F< .gnuspool>
configuration file (current directory)

F<splpd.help>
message file

=head1 ENVIRONMENT

=over 4

=item SPLPRM

space-separated options to override defaults.

=item LPDINTCONF

location of alternative help file.

=back

=head1 SEE ALSO

gspl-lpq(1),
spsyntax(5),
xtlpc(8).

=head1 DIAGNOSTICS

Various diagnostics are read and printed as required from the message
file, by default F<splpd.help>.

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
