=head1 NAME

gspl-ulist - list permissions for users

=head1 SYNOPSIS

B<gspl-ulist>
[ I<-options> ]

=head1 DESCRIPTION

B<gspl-ulist> lists the permissions of users known to the B<GNUspool>
print spooler system.

The invoking user must have I<edit admin file> permission to use
B<gspl-ulist>.

=head1 OPTIONS

=for man
Note that the order of treatment, letters and keywords described below
may be modified by editing the file \fIrest.help\fR \-
see \fIspsyntax\fR\|(5).

The environment variable on which options are supplied is C<GSPL-ULIST>
and the environment variable to specify the help file is
C<SPRESTCONF>.

=over 4

=item -? or +explain

causes a summary of the other options to be displayed without taking
further action.

=item -D or +default-format

cancel the B<-F> option and revert to the default format.

=item -d or +default-line

display an initial line giving the default options (default).

=item -F or +format

format the output according to the I<format> string given.

=item -H or +header

generate a header for each column of the output appropriate for the format.

=item -N or +no-header

cancel the B<-H> option.

=item -n or +numeric-sort

sort the list of users by the numeric user id (default).

=item -S or +no-user-lines

suppress the user lines. It is an error to invoke this and the B<-s>
option as well.

=item -s or +no-default-line

suppress the initial line giving the default options.

=item -U or +user-lines

display the user lines (default).

=item -u or +user-sort

sort the list of users by the user name.

=item +freeze-current

Save all the current options in a F<.gnuspool> file in the current
directory.

=item +freeze-home

Save all the current options in a F<.gnuspool> file in the user's home
directory.

=back

=head2 Format argument.

The format string consists of a string containing the following
character sequences, which are replaced by various user permission
parameters. The string may contain various other printing characters
or spaces as required.

Each column is padded on the right to the length of the longest
entry.

If a header is requested, the appropriate abbreviation is obtained
from the message file and inserted.

=over 4

=item C<%a>

allowed form types

=item C<%b>

allowed printer types

=item C<%c>

allowed class code

=item C<%d>

default priority

=item C<%f>

default form type

=item C<%l>

minimum priority

=item C<%m>

maximum priority

=item C<%n>

maximum copies

=item C<%o>

default printer

=item C<%p>

privileges

=item C<%u>

user name.

=item C<%v>

C<L> if the user is a valid user

=back

The string C<DEFAULT> replaces the user name in the default values
line.

Note that the various strings are read from the message file, so it is
possible to modify them as required by the user.

The default format is

	%u %d %l %m %n %c %p

=head2 Privileges format

The following are output via the C<%p> format. Note that the actual
strings are read from the message file, and are the same ones as are
used by gspl-uchange(1). C<ALL> is displayed if all privileges are set.

=over 8

=item Adm

edit admin file

=item Stp

stop scheduler

=item Form

select forms other than restriction pattern

=item Otherp

select printers other than restriction pattern

=item Cpri

change priority once queued

=item Otherj

edit other users' jobs.

=item Prinq

select printer list

=item Hgo

stop and start printers

=item Anyp

select any priority once queued

=item Cdef

change own default priority within range

=item Addp

add and delete printers

=item Cover

override class

=item Unq

unqueue jobs

=item Votj

view (but not change) other users' jobs

=item Remj

access remote jobs

=item Remp

access remote printers

=item Accessj

access non-displayed job attributes

=item Freeze

freeze parameters from display

=back

=head1 FILES

F<~/.gnuspool>
configuration file (home directory)

F< .gnuspool>
configuration file (current directory)

F<rest.help>
message file

=head1 ENVIRONMENT

=over 4

=item GSPL_ULIST

space-separated options to override defaults.

=item SPRESTCONF

location of alternative help file.

=back

=head1 SEE ALSO

gspl-uchange(1),
gspl-user(1),
spsyntax(5),
gnuspool.conf(5),
gnuspool.hosts(5).

=head1 DIAGNOSTICS

Various diagnostics are read and printed as required from the message
file, by default F<rest.help>.

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
