=head1 NAME

gspl-xmpg - X/Motif spool queue view

=head1 SYNOPSIS

B<gspl-xmpg>

=head1 DESCRIPTION

B<Gspl-Xmpg> is a fully interactive Motif alternative to the standard
print queue manager gspl-pq(1). As with spq(1) the format of the screen
display, the help messages and the command keystrokes can be easily
altered to suit your requirements.

Unlike gspl-pq(1) there are no specific command line options to
B<gspl-xmpg>. The facility to change or specify resources settings for an
X11 (and hence Motif) program on the command line can be used.

=head1 FILES

F<~/.gnuspool>
configuration file (home directory)

F< .gnuspool>
configuration file (current directory)

F<gspl-xmpg.help>
message file

F<gnuspoolptrs>
printers directory

F<spshed_reps>
error log file

=head1 ENVIRONMENT

=over 4

=item GSPL-XMPGCONF

path name of alternative message file.

=back

=head1 SEE ALSO

gspl-pq(1),
gspl-pr(1),
gspl-user(1),
gspl-qdel(1),
gspl-qchange(1),
gspl-qlist(1),
gspl-plist(1),
gnuspool.conf(5),
gnuspool.hosts(5).

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gspl-pq SPQCONF gspl-xmpg
