=head1 NAME

gspl-servinstall - install services

=head1 SYNOPSIS

B<gspl-servinstall>

=head1 DESCRIPTION

B<Gspl-servinstall> installs services in F</etc/services> appropriate
for GNUspool.

=head1 FILES

F</etc/services>

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gspl-user gspl-xuser
