=head1 NAME

gspl-plist - dump out GNUspool printers to a shell script

=head1 SYNOPSIS

B<gspl-plist>
[ I<-D dir> ]
[ I<-e n> ]
[ I<-s> ]
[ I<-f> ]
[ I<-l> ]
I<ptr file> I<outfile>

=head1 DESCRIPTION

B<gspl-plist> converts B<GNUspool> printers held in the spool directory to
an executable shell script which may be used to re-install them. This
may be useful for backup purposes or for one stage in upgrade from one
release of B<GNUspool> to another.

B<gspl-plist> considers a B<GNUspool> spool directory, by default the
current directory, takes the printer file, which is usually
F<spshed_pfile>, and generates a shell script file I<outfile>, which
if executed, would recreate the B<GNUspool> printers with the same options.

B<N.B.> setup files are not copied, this should be done as a separate
exercise. In many cases these can be separately copied over from one
release to the next.

In addition to options, two arguments are always supplied to
B<gspl-plist>.

=over 4

=item Printer list file

This is the file containing the attributes of the printers,
F<spshed_pfile> in the spool directory or as relocated by
re-specifying C<SPOOLDIR>.

=item Output file

This file is created by B<gspl-plist> to contain the executable shell
script, containing gspl-padd(1) commands, which may be used to reinstall
the printers.

=back

=head1 OPTIONS

=over 8

=item -D I<directory>

specifies the source directory for the printers and I<ptr file>. It can be
specified as C<$SPOOLDIR> or C<${SPOOLDIR-/var/spool/gnuspool}> etc and the
environment and/or F<gnuspool.conf> will be interrogated to
interpolate the value of the environment variable given.

If you use this, don't forget to put single quotes around it thus:

 gspl-plist -D '${SPOOLDIR-/var/spool/gnuspool}' ...

otherwise the shell will try to interpret the C<$> construct and not
B<gspl-plist>.

=item -e I<n>

Tolerate I<n> errors of the kinds denoted by the other options before
giving up trying to convert the file.

=item -f

Ignore format errors (invalid form types etc) in the saved printer
file up to the limit of number of errors given by the B<-e> option.

=item -l

Modify the shell script created so that printers recreated with be
"local only" access rather than network wide.

=item -s

Ignore file size errors in the saved printer file (up to the number of
total errors given by the B<-e> option.

=back

=head1 SEE ALSO

gspl-cjlist(8),
gspl-setspdir(8),
gspl-spuconv(8).

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gspl-plist spshed SPOOLDIR
