=head1 NAME

gspl-cjlist - dump out GNUspool jobs to directory

=head1 SYNOPSIS

B<gspl-cjlist>
[ I<-D dir> ]
[ I<-e n> ]
[ I<-u> ]
[ I<-s> ]
[ I<-f> ]
[ I<-m> ]
I<job file> I<outfile> I<workdir>

=head1 DESCRIPTION

B<gspl-cjlist> converts B<GNUspool> job files held in the spool directory to
an executable shell script which may be used to recreate them. This
may be useful for backup purposes or for one stage in upgrading from one
release of B<GNUspool> to another.

The jobs are copied into the backup directory I<workdir>, and the
generated shell script file I<outfile> refers to files in that
directory.

B<gspl-cjlist> will, if required, skip apparent errors in the job file.

In addition to options, three arguments are always supplied to
B<gspl-cjlist>.

=over 4

=item Job list file

This is the file containing the attributes of the jobs,
F<spshed_jfile> in the spool directory, by default,
or as relocated by re-specifying C<SPOOLDIR>.

=item Output file

This file is created by B<gspl-cjlist> to contain the executable shell
script which may be used to create the jobs.

=item Backup directory

This directory is used to hold the job data.

=back

Note that saved jobs make use of the B<-U> option to gspl-pr(1) to set the
ownership correctly but do not attempt to use the B<-E> and B<-o>
options to set external queue or originating hosts.

=head1 OPTIONS

=over 4

=item -D I<directory>

specifies the source directory for the jobs and I<job file> rather
than the current directory. It can be specified as C<$SPOOLDIR> or
C<${SPOOLDIR-/var/spool/gnuspool}> etc and the environment and/or
F<gnuspool.conf> will be interrogated to interpolate the value of
the environment variable given.

If you use this, don't forget to put single quotes around it thus:

 gspl-cjlist -D '${SPOOLDIR-/var/spool/gnuspool}' ...

otherwise the shell will try to interpret the C<$> constructs and not
B<gspl-cjlist>.

=item -e I<n>

Tolerate I<n> errors of the kinds denoted by the other options before
giving up trying to convert the file.

=item -f

Ignore format errors (invalid form types etc) in the saved job file up
to the limit of errors given by the B<-e> option.

=item -m

Create "missing" dummy jobs where the I<job file> refers to jobs not in the
saved directory.

=item -s

Ignore file size errors in the saved job file (up to the number of
total errors given by the B<-e> option).

=item -u

Do not reject the save job file if it contains invalid  user names.

This may be necessary where the job file is corrupted and B<gspl-cjlist>
cannot work out which version it is.

=back

=head1 SEE ALSO

gspl-cplist(8),
gspl-setspdir(8),
gspl-spuconv(8).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gspl-cjlist spshed gspl-pr SPOOLDIR gspl-cplist gspl-setspdir
