=head1 NAME

gspl-lpcover - emulate LP

gspl-lpstatc - emulate LPSTAT

cancel - emulate CANCEL

=head1 SYNOPSIS

B<gspl-lpcover>
[ I<-options> ]
[ I<file> ... ]

B<gspl-lpstatc>
[ I<-options> ]

B<cancel>
I<jobnumber> [ ... ]

=head1 DESCRIPTION

B<gspl-lpcover> may be used instead of the standard B<lp> command. It
converts the options that most B<lp> commands take to the equivalent
gspl-pr(1) commandds and then invokes gspl-pr(1) to submit the print jobs.

The B<gspl-pr> program provides a much greater set of facilities than
B<lp>. Although it is strongly recommended to switch to the gspl-pr(1)
command to take advantage of these, they can be made available to
users of our B<gspl-lpcover> command. This is done by setting up
C<GSPL_PR> in the application or user environment.

B<Gspl-lpcover> is usually installed in place of B<lp> in F</usr/bin>, with
the original binary moved to something like F<old.lp> in the same
directory.

B<Gspl-lpstatc> emulates B<lpstat> as far as is practicable, generating a
report of outstanding print jobs from the print queue in a format
similar to the original B<lpstat>.

B<cancel> is a shell script which invokes gspl-qdel(1) on its arguments.

=head1 OPTIONS

The options below document B<gspl-lpcover> only. Options to B<gspl-lpstatc>
generate a warning message on standard error and are otherwise
ignored. Options to B<gspl-lpcover> which are not documented here are ignored.

=over 8

=item -c

This has no effect, but generates a warning message on standard error,
as with B<GNUspool> spool files are always copied.

=item -d I<name>

Specify printer destination as I<name>. The destination may also be
specified in the environment variable C<LPDEST>, which this option
overrides. An argument of C<any> to B<-d> cancels any existing
C<LPDEST> environment variable.

This is translated directly into a B<-P> option to B<gspl-pr>.

=item -f I<form>

specifies the supplied form type. This is translated directly into an
B<-f> option to B<gspl-pr>.

=item -H I<arg>

There is no direct mapping for the B<-H> argument.

=item -m

Mail user. This is translated directly into an B<-m> option to B<gspl-pr>.

=item -n I<n>

Specify the number of copies. This is translated directly into a B<-c>
option to B<gspl-pr>.

=item -o I<arg>

Only B<-o> C<nobanner>, to suppress the header page, is interpreted
and translated to the B<-s> option to B<gspl-pr>.

=item -P I<arg>

This is translated into B<-R> page range arguments for B<gspl-pr>.

=item -q I<n>

This is translated into a B<-p> argument for B<gspl-pr> scaled
appropriately, taking into account the user's maximum, minimum and
default priorities.

=item -S

This option is ignored.

=item -s

This turns off the B<-v> argument for B<gspl-pr> which is normally
included.

=item -T

This option is ignored.

=item -t <arg>

This is translated to a B<-h> (title) argument to B<gspl-pr>.

=item -w

This is translated directly to the B<-w> (write message) option to
B<gspl-pr>.

=item -y

This option is ignored.

=back

=head1 ENVIRONMENT

=over 8

=item LPDEST

Specify destination for B<gspl-lpcover>.

=item LPSTATFMT

Specify alternate format for B<gspl-lpstatc>.

=back

=head1 DIAGNOSTICS

Various warnings about unimplemented features are printed by
B<gspl-lpcover> and B<gspl-lpstatc>.

Others may be generated by software each invokes.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
