=head1 NAME

gspl-xpq - GTK+ spool queue view

=head1 SYNOPSIS

B<gspl-xpq>

=head1 DESCRIPTION

B<Gspl-xpq> is a fully interactive GTK+ alternative to the standard
print queue manager gspl-pq(1). As with spq(1) the format of the screen
display, the help messages and the command keystrokes can be easily
altered to suit your requirements.

Unlike gspl-pq(1) there are no specific command line options to
B<gspl-xpq>. Options can be set and saved from within the program.

=head1 FILES

F<~/.gnuspool>
configuration file (home directory)

F< .gnuspool>
configuration file (current directory)

F<gspl-xmpq.help>
message file

F<gnuspoolptrs>
printers directory

F<spshed_reps>
error log file

=head1 ENVIRONMENT

=over 4

=item GSPL_XPQCONF

path name of alternative message file.

=back

=head1 SEE ALSO

gspl-pq(1),
gspl-pr(1),
gspl-user(1),
gspl-qdel(1),
gspl-qchange(1),
gspl-qlist(1),
gspl-plist(1),
gnuspool.conf(5),
gnuspool.hosts(5).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gspl-pq SPQCONF gspl-xpq
