=head1 NAME

gspool_close - close a GNUspool connection

=head1 SYNOPSIS

=for man
\&\fB#include <gspool.h>\fR
.PP

=for html
<STRONG>#include &lt;gspool.h&gt;</STRONG>
<BR>

B<int gspool_close(const int> I<fd>B<)>

=head1 DESCRIPTION

The B<gspool_close()> function is used to close a connection to GNUspool.
I<fd> is a file descriptor previously returned by B<gspool_open> or B<gspool_login>.

=head1 RETURN VALUES

B<Gspool_close()> returns 0 if successful or B<GSPOOL_INVALID_FD> (Invalid
File descriptor, a constant defined in F<gspool.h>) if the passed file
descriptor was not valid, perhaps because it was never opened successfully.

=head1 EXAMPLE

An example showing a connection being opened then closed:

 int     fd;
 fd = gspool_open("myhost", (char *)0, 0);
 if (fd < 0) {  /* error handling */
     ...
 }

 /* process connection */

 gspool_close(fd);

=head1 SEE ALSO

gspool_open(3)

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
