=head1 NAME

spd - spool despooler

=head1 SYNOPSIS

B<spd>
I<printer name>
I<printer-number>

=head1 DESCRIPTION

B<spd> is the spool despooler process for the B<GNUspool> spooler and
document management system.

It is only ever intended to be invoked by the scheduler process
spshed(8), and the effect of a user invoking this process is not
defined.

The arguments are the printer name and the I<slot number> in shared
memory which refers to it.

=head1 FILES

F<gnuspool.conf>
master configuration file

F<int-config>
message file

F</var/spool/gnuspool>
spool directory

F<gnuspoolptrs>
printer setup file directory

F<spshed_reps>
error log file

=head1 ENVIRONMENT

=over 4

=item SPOOLDIR

alternative location for spool directory

=item SPROGDIR

alternative location for spool programs

=item SPOOLPT

alternative location for printer descriptions

=back

=head1 SEE ALSO

spshed(8),
spdinit(8),
gnuspool.conf(5),
gnuspool.hosts(5).

=head1 DIAGNOSTICS

B<spd> is usually invoked indirectly, via spshed(8) from system
startup procedures or other programs such as gspl-start(1).

Thereafter it runs as a "daemon process" and diagnostics are not
written to any terminal but to the file F<spshed_reps>.

In the event of any problems this file should be examined.

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
