=head1 NAME

spexec - run commands for macros

=head1 SYNOPSIS

B<spexec>
I<options>

=head1 DESCRIPTION

B<Spexec> runs commands for macros under the identity of the invoking
user. This is required because gspl-pq(1) gspl-xpq(1) gspl-xmpq(1) are set-user
programs (to other than C<root>) and there is an inherent security
breach in many versions of Unix in that such programs cannot divest
themselves of traces of the set-user user id.

This program is only intended for internal use and is not further
documented.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
