=head1 NAME

xilp - LPD protocol server driver (OBSOLETE)

=head1 SYNOPSIS

B<xilp>
I<-H hostname>
[ I<-p port> ]
[ I<-h> ]
[ I<-r> ]
[ I<-# n> ]
[ I<-U user> ]
[ I<-P ptr> ]
[ I<-J name> ]
[ I<-F name> ]
[ I<file> ... ]

=head1 DESCRIPTION

B<xilp> is a terminal server program for use by B<GNUspool> where
the destination is an LPD server.

It has been largely superseded by xtlpc(8).

=head1 OPTIONS

=over 8

=item -H I<hostname>

This is the host name or IP address to be used to access the
printer. In B<GNUspool> setup files, it may be appropriate to
substitute $SPOOLDEV or $SPOOLPTR here.

=item -p I<port number>

This is the port number or service port name to be used.

=item -h

Enable banner page

=item -r

Remove file on completeion

=item -# I<n>

Set number of copies to I<n>.

=item -U I<user>

Set user name to I<user>.

=item -P I<ptr>

Set printer name to I<ptr>

=item -C I<class>

Set printer name to I<class>

=item -J I<file>

Synonym for B<-F>.

=item -F I<file>

Set file name to I<file>.

=back

=head1 DIAGNOSTICS

B<xilp> generates any appropriate diagnostics on standard error.

=head1 EXIT CODES

Normal termination is denoted by an exit code of zero.

Most of the other exit codes are determined by the control file and
can be adjusted by the user as required.

=over 4

=item 1

Device appears to be offline

=item 2

Device error, cannot connect socket etc.

=item 3

Usage error invalid argument etc

=item 4

System error, no service ports etc.

=back

=head1 SEE ALSO

xtelnet(8),
xtlhp(8),
xtftp(8),
xtlpc(8).

=head1 AUTHOR

A N Other, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
