=head1 NAME

xtelnet - reverse telnet terminal server driver

=head1 SYNOPSIS

B<xtelnet>
I<-h hostname>
I<-p port>
[ I<-d> ]
[ I<-l loops> ]
[ I<-L loopwait> ]
[ I<-t sleep> ]
[ I<-s lingertime> ]

=head1 DESCRIPTION

B<xtelnet> is a terminal server program for use by B<GNUspool> where
the destination is a server which accepts "reverse telnet"
protocol. Data is accepted on standard input.

=head1 OPTIONS

=over 8

=item -h I<hostname>

This is the host name or IP address to be used to access the
printer. In B<GNUspool> setup files, it may be appropriate to
substitute C<$SPOOLDEV> or C<$SPOOLPTR> here.

=item -p I<port number>

This is the port number (or name in F</etc/services> to be used. In
B<GNUspool> setup files, it may sometimes be appropriate to substitute
C<$SPOOLDEV> here, but this is unlikely.

=item -l I<n>

Make I<n> connection attempts before giving up trying to connect to
the server.

=item -L I<n>

In conjunction with B<-l> option, sleep I<n> seconds between attempts
to connect to the server.

=item -t I<n>

Sleep I<n> seconds before exiting, after closing the connection to the
server. This is sometimes necessary with some servers, as B<GNUspool>
operates too fast for them. However you may prefer to use the
C<closewait> option in the I<setup file>.

=item -s I<n>

Specify "linger time" in seconds (which may be fractional) for the
connection. This is likewise necessary with some servers.

=item -d

Debug. Displays activities on standard error.

=back

=head1 DIAGNOSTICS

B<xtelnet> generates any appropriate diagnostics on standard
error. Use the C<fberror> and/or C<logerror> keywords in the I<setup
file> to record such errors.

=head1 EXIT CODES

Normal termination is denoted by an exit code of zero.

=over 4

=item 1

Device appears to be offline.

=item 2

Some kind of device error, failure to connect etc.

=item 3

Incorrect usage, unknown option etc.

=item 4

System error, cannot find host name etc.

=back

=head1 SEE ALSO

xilp(8),
xtftp(8),
xtlpc(8),
xtlhp(8).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
