=head1 NAME

xtlpd - LPD protocol server

=head1 SYNOPSIS

B<xtlpd>
I<ctrlfile>

=head1 DESCRIPTION

B<xtlpd> provides a terminal server interface to receive incoming jobs
from LPD protocol clients and direct them to B<GNUspool>.

The argument is the control file.

=head1 DIAGNOSTICS

B<xtlpd> generates any appropriate diagnostics on standard error.

=head1 EXIT CODES

B<xtlpd> forks off as a I<daemon process> and hence it should return
with an exit code of zero. Initial checks may cause it to exit with
other exit codes as follows:

=over 4

=item 1

Usage error, invalid option etc.

=item 2

Cannot open control file.

=item 3

Errors in control file.

=item 4

No spool directory specified in control file.

=item 5

Cannot open spool directory.

=item 6

Cannot create log file.

=item 7

Cannot initialise network.

=back

=head1 FILES

F<xtlpd-ctrl>
standard control file

=head1 SEE ALSO

xtlpc(8),
xtlpq(8),
xtlprm(8).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
