//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sprsetw.rc
//
#define IDR_MAINFRAME                   2
#define IDP_XTENQ_PASSREQ               50
#define IDP_XTENQ_BADPASSWD             51
#define IDP_XTENQ_UNKNOWN               52
#define IDP_XTENQ_BADCLIENT             53
#define IDP_XTENQ_UNKNOWNU              54
#define IDP_CONNDIED                    56
#define IDD_ABOUTBOX                    100
#define IDP_PROGSAVE                    101
#define IDD_FORMDLG                     101
#define IDP_RESTOREOK                   102
#define IDD_HOST                        102
#define IDP_WRONGFORM                   103
#define IDD_LOGINHOST                   103
#define IDP_BADDELIMITER                104
#define IDD_LOGINOUT                    104
#define IDP_STARTPGENDP                 105
#define IDD_PAGE                        105
#define IDP_PRINGNPRIN                  106
#define IDD_PORTNUMS                    106
#define IDP_ZEROCLASS                   107
#define IDD_PROPTS                      107
#define IDP_PREVINSTANCE                108
#define IDD_RETAIN                      108
#define IDD_SECURITY22                  109
#define IDP_WRONGPTR                    109
#define IDS_NOTLOGGED                   110
#define IDD_SIZELIM                     110
#define IDD_USERMAIL                    111
#define IDS_JANUARY                     113
#define IDS_FEBRUARY                    114
#define IDS_MARCH                       115
#define IDS_APRIL                       116
#define IDS_MAY                         117
#define IDS_JUNE                        118
#define IDS_JULY                        119
#define IDS_AUGUST                      120
#define IDS_SEPTEMBER                   121
#define IDS_OCTOBER                     122
#define IDS_NOVEMBER                    123
#define IDS_DECEMBER                    124
#define IDS_SUNDAY                      125
#define IDS_MONDAY                      126
#define IDS_TUESDAY                     127
#define IDS_WEDNESDAY                   128
#define IDS_THURSDAY                    129
#define IDS_FRIDAY                      130
#define IDS_SATURDAY                    131
#define IDD_RETAINABS                   133
#define IDS_UNKNOWN                     140
#define IDS_PROBE                       141
#define IDS_SERVER                      142
#define IDP_NOHOSTSYET                  150
#define IDC_FORMTYPE                    150
#define IDP_NOTSELECTED                 151
#define IDC_HEADER                      151
#define IDP_SUREDEL                     152
#define IDC_SUPPH                       152
#define IDP_NOHOSTNAME                  153
#define IDC_PRINTER                     153
#define IDP_NOALIASNAME                 154
#define IDC_COPIES                      154
#define IDP_ALIASSAMEASHOST             155
#define IDC_SCR_COPIES                  155
#define IDP_BADINETADDR                 156
#define IDC_PRIORITY                    156
#define IDP_HIDCLASH                    157
#define IDC_SCR_PRIORITY                157
#define IDP_HIDCLASHMINE                158
#define IDC_HOSTNAME                    158
#define IDP_ALIASCLASH                  159
#define IDC_ALIASNAME                   159
#define IDP_HOSTCLASH                   160
#define IDC_TIMEOUT                     160
#define IDP_UNKNOWNHOSTNAME             161
#define IDC_SCR_TIMEOUT                 161
#define IDP_MYHOSTNAME                  162
#define IDC_PROBEFIRST                  162
#define IDP_NOTALIVE                    163
#define IDC_UNIXHOST                    163
#define IDP_NO_SERVER                   164
#define IDC_CLIENTHOST                  164
#define IDC_USER                        165
#define IDC_PASSWD                      166
#define IDC_UNIXUSER                    167
#define IDC_WINUSER                     168
#define IDC_LOGIN                       169
#define IDC_LOGOUT                      170
#define IDC_STARTP                      171
#define IDC_SCR_STARTP                  172
#define IDC_ENDP                        173
#define IDC_SCR_ENDP                    174
#define IDC_ALLP                        175
#define IDC_ODDP                        176
#define IDC_EVENP                       177
#define IDC_SWAPOE                      178
#define IDC_DELIMNUM                    179
#define IDC_SCR_DELIMNUM                180
#define IDC_DELIMITER                   181
#define IDC_PPFLAGS                     182
#define IDC_SETDEFAULT                  183
#define IDC_INCALLBY                    184
#define IDC_SCR_INCALLBY                185
#define IDC_APPLYINC                    186
#define IDC_APPLYDEC                    187
#define IDC_CLIENTPORT                  188
#define IDC_SCR_CLIENTPORT              189
#define IDC_PROBEPORT                   190
#define IDC_SCR_PROBEPORT               191
#define IDC_CONNPORT                    192
#define IDC_SCR_CONNPORT                193
#define IDC_VIEWPORT                    194
#define IDC_SCR_VIEWPORT                195
#define IDC_APITCPPORT                  196
#define IDC_SCR_APITCPPORT              197
#define IDC_APIUDPPORT                  198
#define IDC_SCR_APIUDPPORT              199
#define IDP_NO_HOSTFILE                 200
#define IDC_SAVESETTINGS                200
#define IDP_HF_INVALIDHOST              201
#define IDC_VERBOSE                     201
#define IDC_COLON2                      201
#define IDP_HF_BADTIMEOUT               202
#define IDC_TEXTMODE                    202
#define IDC_COLON3                      202
#define IDP_HF_NOALIAS                  203
#define IDC_INTERPOLATE                 203
#define IDC_RETAIN                      204
#define IDC_DIP                         205
#define IDP_GSPU_NOSOCK                 206
#define IDC_SCR_DIP                     206
#define IDP_GSPU_NOBIND                 207
#define IDC_DINP                        207
#define IDP_GSPU_NOSEND                 208
#define IDC_SCR_DINP                    208
#define IDP_GSPU_NORECV                 209
#define IDC_HOLD                        209
#define IDP_GSPU_NVALID                 210
#define IDC_HOUR                        210
#define IDP_CCINIFILE                   211
#define IDC_MIN                         211
#define IDC_WDAY                        212
#define IDC_MDAY                        213
#define IDC_MON                         214
#define IDC_SCR_HOUR                    215
#define IDC_SCR_MIN                     216
#define IDC_SCR_WDAY                    217
#define IDC_SCR_MDAY                    218
#define IDC_SCR_MON                     219
#define IDC_COLON                       220
#define IDC_SETALL                      221
#define IDC_CLEARALL                    222
#define IDC_CC_A                        223
#define IDC_CC_B                        224
#define IDC_CC_C                        225
#define IDC_CC_D                        226
#define IDC_CC_E                        227
#define IDC_CC_F                        228
#define IDC_CC_G                        229
#define IDC_CC_H                        230
#define IDC_CC_I                        231
#define IDC_CC_J                        232
#define IDC_CC_K                        233
#define IDC_CC_L                        234
#define IDC_CC_M                        235
#define IDC_CC_N                        236
#define IDC_CC_O                        237
#define IDC_CC_P                        238
#define IDC_CC_A2                       239
#define IDC_CC_B2                       240
#define IDC_CC_C2                       241
#define IDC_CC_D2                       242
#define IDC_CC_E2                       243
#define IDC_CC_F2                       244
#define IDC_CC_G2                       245
#define IDC_CC_H2                       246
#define IDC_DELHOURS                    246
#define IDC_CC_I2                       247
#define IDC_DELMINS                     247
#define IDC_CC_J2                       248
#define IDC_DELSECS                     248
#define IDC_CC_K2                       249
#define IDC_SCR_DELHOURS                249
#define IDC_CC_L2                       250
#define IDC_SCR_DELMINS                 250
#define IDC_CC_M2                       251
#define IDC_SCR_DELSECS                 251
#define IDC_CC_N2                       252
#define IDC_CC_O2                       253
#define IDC_CC_P2                       254
#define IDC_LOCALONLY                   255
#define IDC_LIMIT                       256
#define IDC_SCR_LIMIT                   257
#define IDC_LIMITK                      258
#define IDC_LIMITP                      259
#define IDC_ERRLIMIT                    260
#define IDC_MAIL                        261
#define IDC_WRITE                       262
#define IDC_MATTN                       263
#define IDC_WATTN                       264
#define ID_PROGRAM_SAVE                 32768
#define ID_NETWORK_ADDNEWHOST           32769
#define ID_NETWORK_DELETEHOST           32770
#define ID_NETWORK_CHANGEHOST           32771
#define ID_NETWORK_SETASSERVER          32772
#define ID_DEVICES_LOCALPRINTER         32773
#define ID_OPTIONS_RESTOREDEFAULTS      32774
#define ID_OPTIONS_FORMANDCOPIES        32775
#define ID_OPTIONS_USERANDMAIL          32776
#define ID_OPTIONS_PAGE                 32777
#define ID_OPTIONS_RETAIN               32778
#define ID_OPTIONS_SECURITY             32779
#define ID_OPTIONS_PROGRAMOPTIONS       32780
#define ID_OPTIONS_SIZELIMIT            32781
#define ID_PROGRAM_PORTSETTINGS         32782
#define ID_PROGRAM_LOGINORLOGOUT        32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         267
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
