#! /bin/sh
#
#   Copyright 2008 Free Software Foundation, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

rm TAGS
etags hdrs/*.h hdrs/infiles.h.in
etags -a *.[ch]
etags -a lib/*.[ch]
etags -a inline/*.[ch]
etags -a gtk/*.[ch]
etags -a motif/*.[ch]
etags -a apilib/*.[ch]
etags -a loccgi/*.[ch]
etags -a remcgi/*.[ch]
etags -a ins/*.[chyl]
etags -a termserv/*.[chyl]
etags -a lpdint/*.[chyl]
