# Copyright (C) 2011  Free Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Originally written by John Collins <jmc@xisl.com>.

# Table of printer attributes

# List of attributes by key
# Value is tuple with first element the type (a string) and the second argument
# the value, possibly a list

from ipp import *

Printer_atts = {
    'auth-info-required':   (IPP_TAG_KEYWORD,   'none'),
    'charset-configured':   (IPP_TAG_CHARSET,	'utf-8'),
    'charset-supported':    (IPP_TAG_CHARSET,	['us-ascii', 'utf-8']),
    'color-supported':      (IPP_TAG_BOOLEAN,	1),
    'compression-supported':(IPP_TAG_KEYWORD,   'none'),
    'copies-default':       (IPP_TAG_INTEGER,   1),
    'copies-supported':     (IPP_TAG_RANGE,     (1, 255)),
    'cups-version':         (IPP_TAG_TEXT,	'1.4.4'),
    'device-uri':           (IPP_TAG_URI,	'gs://net/%(PTRNAME)s'),
    'document-format-default':(IPP_TAG_MIMETYPE,    'application/octet-stream'),
    'document-format-supported':(IPP_TAG_MIMETYPE,
                   ['application/octet-stream',
                    'application/openofficeps',
                    'application/pdf',
                    'application/postscript',
                    'application/vnd.cups-banner',
                    'application/vnd.cups.command',
                    'application/vnd.cups.pdf',
                    'application/vnd.cups-postscript',
                    'application/vnd.cups-raw',
                    'application/vnd.hp-hpgl',
                    'application/vnd.x-cshell',
                    'application/x-csource',
                    'application/x-perl',
                    'application/x-shell',
                    'image/gif',
                    'image/jpeg',
                    'image/png',
                    'image/tiff',
                    'image/x-bitmap',
                    'image/x-photocd',
                    'image/x-portable-anymap',
                    'image/x-portable-bitmap',
                    'image/x-portable-graymap',
                    'image/x-portable-pixmap',
                    'image/x-sgi-rgb',
                    'image/x-sun-raster',
                    'image/x-xbitmap',
                    'image/x-xpixmap',
                    'text/html',
                    'text/plain']),
    'finishings-default':   (IPP_TAG_ENUM,      3),
    'finishings-supported': (IPP_TAG_ENUM,	3),
    'generated-natural-language-supported':	(IPP_TAG_LANGUAGE,  'en-us'),
    'ippget-event-life':    (IPP_TAG_INTEGER,	15),
    'ipp-versions-supported':	(IPP_TAG_KEYWORD,   ['1.0', '1.1', '2.0', '2.1']),
    'job-creation-attributes-supported':
            (IPP_TAG_KEYWORD, ['copies',
                               'finishings',
                               'ipp-attribute-fidelity',
                               'job-hold-until',
                               'job-name',
                               'job-priority',
                               'job-sheets',
                               'media',
                               'media-col',
                               'multiple-document-handling',
                               'number-up',
                               'output-bin',
                               'orientation-requested',
                               'page-ranges',
                               'print-quality',
                               'printer-resolution',
                               'sides']),
    'job-hold-until-default':   (IPP_TAG_KEYWORD,   'no-hold'),
    'job-hold-until-supported': (IPP_TAG_KEYWORD,
                                ['no-hold',
                                 'indefinite',
                                 'day-time',
                                 'evening',
                                 'night',
                                 'second-shift',
                                 'third-shift',
                                 'weekend']),
    'job-k-limit':          (IPP_TAG_INTEGER,   0),
    'job-page-limit':       (IPP_TAG_INTEGER,	0),
    'job-priority-default': (IPP_TAG_INTEGER,   50),
    'job-priority-supported':(IPP_TAG_INTEGER,	100),
    'job-quota-period':     (IPP_TAG_INTEGER,	0),
    'job-settable-attributes-supported':    (IPP_TAG_KEYWORD,
                        ['copies', 'finishing', 'job-hold-until',
                         'job-name', 'job-priority', 'media',
                         'media-col', 'multiple-document-handling',
                         'number-up', 'output-bin', 'orientation-requested',
                         'page-ranges', 'print-quality', 'printer-resolution',
                         'sides']),
    'job-sheets-default':   (IPP_TAG_NAME,  ['none', 'none']),
    'job-sheets-supported': (IPP_TAG_NAME,  ['none', 'classified',
                                            'confidential', 'secret',
                                            'standard', 'topsecret', 'unclassified']),
    'marker-change-time':   (IPP_TAG_INTEGER,	0),
    'media-bottom-margin-supported':	(IPP_TAG_INTEGER,   [1270, 0]),
    'media-col-supported':  (IPP_TAG_KEYWORD,
                            ['media-bottom-margin',
                             'media-left-margin',
                             'media-right-margin',
                             'media-size',
                             'media-source',
                             'media-top-margin',
                             'media-type']),
    'media-default':        (IPP_TAG_KEYWORD, 'iso_a4_210x297mm'),
    'media-left-margin-supported':	(IPP_TAG_INTEGER,   [635, 342, 0, 317]),
    'media-right-margin-supported':	(IPP_TAG_INTEGER,   [635, 342, 0, 317]),
    'media-source-supported':
                            (IPP_TAG_KEYWORD,
                               ['auto',
                                'photo-tray',
                                'top',
                                'bottom',
                                'cddvdtray',
                                'envelope',
                                'large-capacity',
                                'manual',
                                'alternate']),
    'media-supported':      (IPP_TAG_KEYWORD,
                            ['na_letter_8.5x11in',
                             'iso_a4_210x297mm',
                             'oe_photo_4x6in',
                             'oe_photo5x7_5x7in',
                             'oe_photo-tear-off_4x6in',
                             'oe_3x5_3x5in',
                             'oe_5x8_5x8in',
                             'iso_a5_148x210mm',
                             'iso_a6_105x148mm',
                             'om_a6-tear-off_104.77x148.16mm',
                             'om_b5-jis_182.03x257.17mm',
                             'om_cddvd80_83.6x83.6mm',
                             'oe_cddvd120_5x5in',
                             'na_number-10_4.125x9.5in',
                             'iso_c5_162x229mm',
                             'iso_c6_114x162mm',
                             'iso_dl_110x220mm',
                             'om_env-isob5_176.03x250.11mm',
                             'na_monarch_3.875x7.5in',
                             'na_executive_7.25x10.5in',
                             'oe_flsa_8.5x13in',
                             'om_hagaki_99.83x148.16mm',
                             'na_legal_8.5x14in',
                             'om_oufuku_200.02x148.16mm',
                             'oe_w558h774_7.75x10.75in',
                             'om_w612h935_215.9x329.84mm',
                             'custom_min_1x4in',
                             'custom_max_13x19in']),
    'media-top-margin-supported':	(IPP_TAG_INTEGER, [317, 0]),
    'multiple-document-handling-supported': (IPP_TAG_KEYWORD,
                            ['separate-documents-uncollated-copies',
                             'separate-documents-collated-copies']),
    'multiple-document-jobs-supported': (IPP_TAG_BOOLEAN, 1),
    'multiple-operation-time-out':	(IPP_TAG_INTEGER, 300),
    'natural-language-configured':	(IPP_TAG_LANGUAGE, 'en-us'),
    'notify-attributes-supported':	(IPP_TAG_KEYWORD,
                            ['printer-state-change-time',
                             'notify-lease-expiration-time',
                             'notify-subscriber-user-name']),
    'notify-events-default':  (IPP_TAG_KEYWORD, 'job-completed'),
    'notify-events-supported':  (IPP_TAG_KEYWORD,
                            ['job-completed',
                             'job-config-changed',
                             'job-created',
                             'job-progress',
                             'job-staged-changed',
                             'job-stopped',
                             'printer-added',
                             'printer-changed',
                             'printer-config-changed',
                             'printer-deleted',
                             'printer-finishings-changed',
                             'printer-media-changed',
                             'printer-modified',
                             'printer-restarted',
                             'printer-shutdown',
                             'printer-state-changed',
                             'printer-stopped',
                             'server-audit',
                             'server-restarted',
                             'server-started',
                             'server-stopped']),
    'notify-lease-duration-default':	(IPP_TAG_INTEGER, 86400),
    'notify-lease-duration-supported':	(IPP_TAG_RANGE, (0, 0x7fffffff)),
    'notify-max-events-supported':	(IPP_TAG_INTEGER, 100),
    'notify-pull-method-supported':	(IPP_TAG_KEYWORD, 'ippget'),
    'notify-schemes-supported': (IPP_TAG_KEYWORD, ['dbus', 'mailto', 'rss']),
    'number-up-default':	(IPP_TAG_INTEGER, 1),
    'number-up-supported':	(IPP_TAG_INTEGER, [1, 2, 4, 6, 9, 16]),
    'operations-supported':	(IPP_TAG_ENUM,
                        [2,4,5,6,8,9,10,11,12,13,16,17,18,19,20,21,22,23,24,25,
                         26,27,28,34,35,37,38] + range(16385,16400) + [16423]),
    'orientation-requested-supported': (IPP_TAG_ENUM, [3,4,5,6]),
    'output-bin-default':	(IPP_TAG_KEYWORD, 'face-down'),
    'output-bin-supported':	(IPP_TAG_KEYWORD, 'face-down'),
    'page-ranges-supported':	(IPP_TAG_BOOLEAN,   1),
    'pages-per-minute':         (IPP_TAG_INTEGER, 1),
    'pages-per-minute-color':	(IPP_TAG_INTEGER, 1),
    'pdl-override-supported':	(IPP_TAG_KEYWORD, 'not-attempted'),
    'port-monitor':             (IPP_TAG_NAME, 'none'),
    'port-monitor-supported':   (IPP_TAG_NAME, 'none'),
    'printer-commands': (IPP_TAG_KEYWORD, ['AutoConfigure', 'Clean', 'PrintSelfTestPage']),
    'printer-current-time':	(IPP_TAG_DATE, '%(NOW)s'),
    'printer-error-policy':	(IPP_TAG_NAME, 'retry-job'),
    'printer-error-policy-supported':
                    (IPP_TAG_NAME,
                    ['abort-job', 'retry-current-job', 'retry-job', 'stop-printer']),
    'printer-info':	(IPP_TAG_TEXT, 'OVERRIDE_ME'),
    'printer-is-accepting-jobs':    (IPP_TAG_BOOLEAN, 1),
    'printer-is-shared':            (IPP_TAG_BOOLEAN, 1),
    'printer-location':             (IPP_TAG_TEXT, 'Local Printer'),
    'printer-make-and-model':       (IPP_TAG_TEXT, 'CUPSPY virtual printer'),
    'printer-more-info':            (IPP_TAG_URI, "http://%(SERVERIP)s:631/printers/%(PTRNAME)s"),
    'printer-name':         (IPP_TAG_NAME, '%(PTRNAME)s'),
    'printer-op-policy':    (IPP_TAG_NAME, 'default'),
    'printer-op-policy-supported':  (IPP_TAG_NAME, ['authenticated', 'default']),
    'printer-resolution-default':   (IPP_TAG_RESOLUTION, (600, 600, 3)),
    'printer-resolution-supported': (IPP_TAG_RESOLUTION, (600, 600, 3)),
    'printer-settable-attributes-supported':
                (IPP_TAG_KEYWORD, ['printer-info', 'printer-location']),
    'printer-state':        (IPP_TAG_ENUM, IPP_PRINTER_IDLE),
    'printer-state-change-time':    (IPP_TAG_INTEGER, '%(STATECHANGE)s'),
    'printer-state-message':	(IPP_TAG_TEXT, ''),
    'printer-state-reasons':	(IPP_TAG_KEYWORD, 'none'),
    'printer-type':             (IPP_TAG_ENUM, 8425500),
    'printer-up-time':          (IPP_TAG_INTEGER, '%(UPTIME)s'),
    'printer-uri-supported':	(IPP_TAG_URI, "ipp://%(SERVERIP)s:631/printers/%(PTRNAME)s"),
    'print-quality-default':	(IPP_TAG_ENUM, 4),
    'print-quality-supported':	(IPP_TAG_ENUM, 4),
    'queued-job-count':         (IPP_TAG_INTEGER, 0),
    'server-is-sharing-printers':   (IPP_TAG_BOOLEAN, 0),
    'sides-default':	(IPP_TAG_KEYWORD, 'one-sided'),
    'sides-supported':  (IPP_TAG_KEYWORD, ['one-sided', 'two-sided-long-edge', 'two-sided-short-edge']),
    'uri-authentication-supported':	(IPP_TAG_KEYWORD, 'requesting-user-name'),
    'uri-security-supported':	(IPP_TAG_KEYWORD, 'none') }
