// Copyright (c) Xi Software Ltd. 1992.
//
// files.h: created by John Collins on Fri Oct 16 1992.
//----------------------------------------------------------------------
// $Header: /sources/gnuspool/gnuspool/MSWIN/INCLUDE/FILES.H,v 1.1 2008/08/18 16:25:54 jmc Exp $
// $Log: FILES.H,v $
// Revision 1.1  2008/08/18 16:25:54  jmc
// Initial revision
//
//----------------------------------------------------------------------

#define	XI_SOFTWARE	"Xi Software"
#define	PRODNAME	"Xi-Text"
#define	DEFBASED	"\\XITEXT"

#define	SPUNAME			"spooler"
#define	HOSTFILE		"hosts"
#define	INIFILE			"xitext.ini"

#define	CONNSERVNAME	"xitext"
#define	PROBESERVNAME	"xitext"
#define	FEEDSERVNAME	"spq"
#define	QSERVNAME		"xtnetsrv"
#define	UASERVNAME		"xtnetsrv"
                                
//  Default port numbers
                                
#define	DEF_CONNPORTNUM		2000
#define	DEF_PROBEPORTNUM	2000
#define	DEF_FEEDPORTNUM		2100
#define	DEF_SERVPORTNUM		2200	// Default port number for server
#define	DEF_INPORTNUM		2310	// Default port number for local printers
#define	DEF_TCPAPIPORTNUM	2210	// Default port number for API TCP
#define	DEF_UDPAPIPORTNUM	2210	// Default port number for API UDP
